### ISSUE TITLE
Modifier un label / textField depuis le code

### ISSUE THREAD

**Issue by ghost** [seinecle/codapps#1]
Bonjour,

Comment puis-je modifier le label / textField depuis le code et non pas directement depuis le GUI s'il vous plait ?

J'ai cru comprendre qu'on peut récupérer la variable en mettant "gui_label1" si mon label s'appelle "label1" dans la class où le screen a été créé.
Cependant dois-je redéclarer la variable en tant que Label en mettant : "Label gui_label1 = new Label()" ?

**Comment by seinecle** [comment]
Non pas besoin de re-déclarer. Depuis la classe (le fichier) du `Form` où le Component a été créé via le GUI Builder, il faut faire:

`this.gui_Label1`

Voir [un exemple dans cette lecon](https://seinecle.github.io/codapps/generated-html/adding-labels-and-buttons.html#anchor-set-text-label-in-code)

**Comment by ghost** [comment]
Merci beaucoup
