### ISSUE TITLE
Déplacer les components dans le GUI 

### ISSUE THREAD

**Issue by tristan-baraille** [seinecle/codapps#10]
Bonjour, 

Quand j'essaye de glisser des components (Label et Button) dans ma Form1, je ne peux pas les placer où je veux et le programme les place automatiquement les uns à la suite des autres en haut à gauche, dans l'emplacement en rouge. 

![deplacement impossible](https://user-images.githubusercontent.com/35726197/35562677-61482326-05b4-11e8-82c7-1fcebbad3301.png)

Par ailleurs, j'ai un autre problème qui est peut-être une conséquence du premier : quand je visualise mon application, après avoir cliqué sur le bouton, le text "Pressed!" ne s'affiche que partiellement. Voici la ligne de code et l'écran de prévisualisation après avoir cliqué sur le bouton :

![affichage partiel](https://user-images.githubusercontent.com/35726197/35562866-0fb9beec-05b5-11e8-9dc7-4b98fc7a7f1b.png)

![affichage partiel 2](https://user-images.githubusercontent.com/35726197/35562881-1df4077e-05b5-11e8-8673-11767a0d3787.png)

Les deux problèmes sont-ils liés ?

**Comment by seinecle** [comment]
- 1er problème:

utilisez les deux pointes de flèche (très discrètes) juste sous le panneau en haut à gauche pour déplacer vos Components. La flèche n° 2 pointe dessus [sur cette copie d'écran](https://camo.githubusercontent.com/83a752b3410026157de4408eb049c07c3bae30b7/68747470733a2f2f646f63732e676f6f676c652e636f6d2f64726177696e67732f642f652f32504143582d317652334a50365f6b6e5768306e6e54776e595955492d474e7878724a7773504e37573063696d463931586b543864787442465a5552644a6e31736a356a3375766d655f41466a58784d3258785a734d2f7075623f773d3134333426683d373931).

- 2e problème:

utilisez une Span Label plutôt qu'une Label, cela vous assure que votre texte ne sera pas coupé. [Voir cette leçon](https://seinecle.github.io/codapps/generated-html/adding-labels-and-buttons.html#_c_label_or_span_label).

Merci de me prévenir ici par un message si cela résout vos problèmes.

**Comment by tristan-baraille** [comment]
Bonjour, 

Merci pour cette réponse. 

Concernant le premier problème, il semblerait que les flèches sous le panneau en haut à gauche ne changent que l'ordre des Components dans la liste, mais ne permettent pas de déplacer les Components dans la Form. 

Après plusieurs essais avec une SpanLabel, en ayant modifié la ligne de code à insérer - j'ai modifié "this.gui_Label.setText("pressed!");" par "this.gui_Span_Label.setText("pressed!");" - je n'arrivais même plus à ouvrir la visualisation de mon application, peut-être à cause de manipulations que j'avais faites auparavant... 

J'ai donc complètement supprimé ma Form1 et repris le Module 2 depuis le début. Cette fois par contre, je pouvais librement placement les Components dans ma Form1 sur le GUI. J'ai à nouveau utilisé une SpanLabel et j'ai fait la même modification que plus haut ; cette fois la visualisation s'est lancé et la commande s'est parfaitement exécuté, mon texte n'était pas coupé. 

Mes problèmes sont donc résolus pour le moment, merci pour votre aide !

**Comment by seinecle** [comment]
Bonjour,

Effectivement changer les lignes de code directement peut être utile mais cela peut aussi vite "casser" l'application si on n'est pas sûr de ce que l'on fait.

Sur le placement des Components "ou l'on veut" sur le Form: _attention_!

- effectivement par défaut les Components qu'on ajoute sont mis en haut à gauche et on ne peut pas les placer librement. Mais ce n'est pas un bug, c'est parce qu'il y a toute une logique pour le placement des Components, qui relève des Layouts et des Containers. Il y a une leçon dédiée à chacun de ces concepts ([Layout](https://seinecle.github.io/codapps/generated-html/using-layouts.html), [Containers](https://seinecle.github.io/codapps/generated-html/using-containers.html)) et c'est en la suivant que vous arriverez à placer vos Components comme vous le souhaitez.

- Mais en re-créant un Form, vous arrivez maintenant à placer les Components là où vous le souhaitez... je pense que vous avez laissé l'option "Auto Layout" cochée quand vous avez créé le Form. Alors, en effet, tout devient plus simple. _Sauf que ce feature n'est pas encore stable_ et je pense que des bugs vont se produire, du type: "tout est clean sur mon GUI Builder mais quand je fais une preview de mon app, tout est décalé / ne correspond pas à ce que j'ai fait".

J'ai donc choisi pour ce cours de vous demander de ne pas créer de Form en auto layout, et de suivre la leçon sur les Containers et Layout pour placer ses Components.

J'espère que cela clarifie?

**Comment by tristan-baraille** [comment]
Il me semble que j'ai décoché cette option en recréant le Form. Existe-t-il un moyen de vérifier si cette option est activée dans le Form que j'ai actuellement ?

**Comment by seinecle** [comment]
Oui: si vous êtes en Auto Layout,

- il y a comme une règle graduée sur les côtés haut et gauche de votre Form.
- vos Components peuvent être déplacés n'importe où sur le Form.
- votre Form s'appelle "FormAutoLayout" dans le panneau en haut à gauche

**Comment by tristan-baraille** [comment]
Effectivement j'étais bien en Auto Layout ; j'ai effacé et recréé un Form avec le même nom en décochant l'Auto Layout et en veillant à utiliser un SpanLabel pour que mon texte ne soit pas coupé. Tout fonctionne bien jusque-là, merci !
