### ISSUE TITLE
Où placer ces lignes ? 

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#100]
Bonjour Monsieur, 

Je ne sais pas où placer ces lignes: 

```
long lastTimeScoreWasComputed; 

private void computeScore() { 
    long currentTimeInSeconds = System.currentTimeMillis() / 1000; 
    long lastTimeScoreWasComputedInSeconds = lastTimeScoreWasComputed / 1000;  

    if (currentTimeInSeconds != lastTimeScoreWasComputedInSeconds) {  
        score = score + myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;  
        scoreLabel.setText(score + " cookies");  
        lastTimeScoreWasComputed = System.currentTimeMillis();  
    }
}
```

Et pareil pour ces lignes la: 

```
float cookiesPerSecond; 

private void computeCookiesPerSecond() {
    cookiesPerSecond =  myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;
    cookiesPerSecondLabel.setText(cookiesPerSecond + " cookies per second"); 

}
```

Faut il les mettre après: 

```
public Form1() {
     registerAnimated(this); 

```
ou bien avant: 

```
@Override 
public boolean animate() {
    // write anything you want here
    return true; 
    }


```Merci !

**Comment by seinecle** [comment]
Bonjour,

**1. Où déclarer les variables comme `long lastTimeScoreWasComputed;` ou `float cookiesPerSecond; ` ?**

- les variables qui sont rattachées à une méthode sont déclarées **dans** cette méthode. Concrètement, si vous avez une variable dont l'existence est "cantonnée" à une méthode (elle est utilisée dans la méthode mais ne sert à rien une fois que la méthode est exécutée), alors vous la déclarez dans cette méthode.

- les variables qui ont besoin de conserver une existence "tout au long du jeu" ou "entre l'exécution de deux méthodes", comme le score, ou le score par seconde, ou "le temps écoulé depuis le dernier calcul de score", **doivent être déclarées hors des méthodes, "en tête" de classe (en haut du fichier)**. On les appelle des variables **globales**. On les déclare donc ici:

```
public class Form1 extends com.codename1.ui.Form {

  Resources theme = Resources.getGlobalResources();
  Image farmPic = theme.getImage("farm_50x37.png");
  Image clickPic = theme.getImage("click_50x64.png");
  Image cookieCentraPic = theme.getImage("cookie_200x200.png");
  Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
  // toutes vos variables globales

```

**2. Dans quel ordre écrire les méthodes dans le fichier?**

Cela n'a pas d'importance. Par convention, on écrit la méthode constructeur (celle qui porte le même nom que la classe, et qui est exécutée quand la classe est instantiée) en premier, juste après la déclaration des variables globales.

**Comment by Clemencegiry** [comment]
Merci, je dois avoir un problème parce que mon application ne marche toujours pas...

![capture d ecran 2018-03-19 a 19 13 26](https://user-images.githubusercontent.com/35694045/37614033-df6dae54-2ba9-11e8-95e8-e1e810ed4893.png)

**Comment by seinecle** [comment]
Bonjour,

C'est un problème différent. Pouvez-vous poster le code de votre fichier svp? (en copiant collant le texte, pas de copie d'écran. Le message d'erreur que vous postez indique une erreur autour de la ligne 15.

En fait, je crois voir le problème: vous avez créé par erreur deux fichiers qui viennent brouiller le code Supprimez les fichiers cookieperSecondLabel.java et scoreLabel.java (que vous voyez dans NetBeans sur la gauche à côté de Form1. java et MyApplication.java).

**Comment by Clemencegiry** [comment]
J'ai supprimé les 2 fichiers dont vous parliez mais d'autres problèmes sont apparus...

Voici le code du fichier: 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.hotmail.clemencegiry.myfirstapp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

/**
 *
 * @author clemence
 */
public class Form1 extends com.codename1.ui.Form {
 Resources theme = Resources.getGlobalResources(); 
 float score = 0f;
 Parameters myParameters = new Parameters();
 Image farmPic = theme.getImage("farm_50x37.png");
 Image clickPic = theme.getImage("click_50x64.png");
 Image cookieCentraPic =theme.getImage("cookie_200x200.png");
 Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
 
 long lastTimeScoreWasComputed; 
 long lastAnimatedTime; 

private void computeScore() { 
    long currentTimeInSeconds = System.currentTimeMillis() / 1000; 
    long lastTimeScoreWasComputedInSeconds = lastTimeScoreWasComputed / 1000;  

    if (currentTimeInSeconds != lastTimeScoreWasComputedInSeconds) {  
        score = score + myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;  
        scoreLabel.setText(score + " cookies");  
        lastTimeScoreWasComputed = System.currentTimeMillis();  
    }
}
float cookiesPerSecond; 

private void computeCookiesPerSecond() {
    cookiesPerSecond =  myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;
    cookiesPerSecondLabel.setText(cookiesPerSecond + "cookies per second"); 

}
 
 public Form1() {
     registerAnimated(this); 
   
     //we create a Container that will contain everything in the "North" part of the
//BorderLayout:
Container northRegion = new Container();
//we choose a BorderLayout for this container:
BorderLayout borderLayoutNorth = new BorderLayout();
northRegion.setLayout(borderLayoutNorth);
//we create a Container that will contain everything in the 2nd row of the screen:
Container centerRegion = new Container();
//we choose a Grid Layout for this container:
GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
centerRegion.setLayout(gridLayoutFourByOne);
//we set this region to be scrollable, because there is too much content to fit
centerRegion.setScrollableY(true);
//we create a Container that will enclose everything in the 3rd row:
Container southRegion = new Container();
//we choose a Border Layout for this container:
BorderLayout blSouth = new BorderLayout();
southRegion.setLayout(blSouth);

this.addComponent(northRegion);
this.addComponent(centerRegion);
this.addComponent(southRegion);
    
// creating the cookie central button
ScaleImageButton cookieCentral = new ScaleImageButton(); 
cookieCentral.setIcon(cookieCentraPic); 
cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT);
cookieCentral.getPressedStyle().setBgImage(cookiePressedPic); 

// these lines of code should go inside  public Form1() { }
Label scoreLabel = new Label();
scoreLabel.setText("0 cookies");
scoreLabel.getStyle().setAlignment(Component.CENTER); //centering the text

Label cookiesPerSecondLabel = new Label();
cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER); 

northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

MultiButton autoclickButton = new MultiButton("Auto click"); 
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\""); 
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");

MultiButton grandmaButton = new MultiButton("Grandma");
     Image grandmaPic = null;
grandmaButton.setIcon(grandmaPic); 
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

//The farm
MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
centerRegion.add(farmButton);

cookieCentral.addActionListener(  
                (event) -> {
                score = score + 1;
                scoreLabel.setText(score + "cookies");
                }
        );

autoclickButton.addActionListener( 
        (event) -> {
            if (score >= myParameters.autoclickPrice) {
                myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                score = score - myParameters.autoclickPrice;
                myParameters.autoclickProd = myParameters.autoclickProd * myParameters.rateIncreaseProd;
                myParameters.autoclickPrice = myParameters.autoclickPrice * myParameters.rateIncreasePrice;
                autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice + " cookies. Owned: " + myParameters.autoclickOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
); 

grandmaButton.addActionListener(
        (event) -> {
            if (score >= myParameters.grandmaPrice) {
                myParameters.grandmaOwned = myParameters.grandmaOwned + 1;
                score = score - myParameters.grandmaPrice;
                myParameters.grandmaProd = myParameters.grandmaProd * myParameters.rateIncreaseProd;
                myParameters.grandmaPrice = myParameters.grandmaPrice * myParameters.rateIncreasePrice;
                grandmaButton.setTextLine4("price: " + myParameters.grandmaPrice + " cookies. Owned: " + myParameters.grandmaOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
);

farmButton.addActionListener(
        (event) -> {
            if (score >= myParameters.farmPrice) {
                myParameters.farmOwned = myParameters.farmOwned + 1;
                score = score - myParameters.farmPrice;
                myParameters.farmProd = myParameters.farmProd * myParameters.rateIncreaseProd;
                myParameters.farmPrice = myParameters.farmPrice * myParameters.rateIncreasePrice;
                farmButton.setTextLine4("price: " + myParameters.farmPrice + " cookies. Owned: " + myParameters.farmOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
);

 }
 
 @Override 
public boolean animate() {
    if (System.currentTimeMillis()/100 > lastAnimatedTime/100 ){
    computeScore();
    computeCookiesPerSecond();
    lastAnimatedTime = System.currentTimeMillis();
    return true; 
    } else {
        return false;
    }
    }

}

Je joins également le message d'erreur qui s'affiche: 

![capture d ecran 2018-03-19 a 23 46 35](https://user-images.githubusercontent.com/35694045/37626381-1b34fa66-2bd0-11e8-889f-b8d0f5abe9dd.png)

Merci !

**Comment by seinecle** [comment]
En style télégraphique car je suis off:

Vos deux variables:

Label cookiesPerSecondLabel = new Label();

et 

Label scoreLabel = new Label();

qui sont pour l'instant dans votre méthode Form1 doivent être déplacées en tête de class, au même endroit que là où vous déclarez les variables pour les images.

**Comment by seinecle** [comment]
Voir ma réponse à l'issue #96

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
