### ISSUE TITLE
mauvais format et non mise à jour du label cookies per second 

### ISSUE THREAD

**Issue by ClovisLF** [seinecle/codapps#101]
![capture d ecran 2018-03-19 a 12 28 37](https://user-images.githubusercontent.com/36734464/37593142-41b2a0b2-2b71-11e8-92f1-3e9e78abd356.png)

Le form 1 n'est pas adapté à la taille de l'écran. 
mon cookiePerSecondLabel ne se met pas à jour.

![capture d ecran 2018-03-19 a 12 32 24](https://user-images.githubusercontent.com/36734464/37593273-aa687a8c-2b71-11e8-8b65-73c12a3f9051.png)

**Comment by seinecle** [comment]
Bonjour,
Il faut changer le type de téléphone de la preview: [voir ici](https://emlyon.github.io/codapps/generated-html/creating-your-first-project-and-previewing-your-app.html#_b_adjusting_the_size_of_the_skin_to_the_screen).

Pour l'update du cookie par seconde, il faudrait que je puisse voir tout votre fichier Form1. Pouvez-vous le copier coller ici svp? (pas en copie d'écran, mais le texte lui-même). Merci!

**Comment by seinecle** [comment]
Bonjour,  la dernière réponse à cette issue date de 6 jours. Je la clos en la  considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si  vous avez une nouvelle question, merci de ne pas réouvrir cette issue,  mais créez-en plutôt une autre.
