### ISSUE TITLE
Non fonctionnement de Net Beans

### ISSUE THREAD

**Issue by MathildeSe** [seinecle/codapps#103]
Bonjour, 
Net Beans ne fonctionnant plus sur mon ordinateur suite à une mise à jour, et après être allée voir le Scope de l'école, je n'ai pas eu le choix que de désinstaller le programme et de le réinstaller. Petit problème, je ne peux plus installer le plugin Codename One qui n'apparait plus dans la liste des plugins disponibles. Je voulais donc savoir comment je pouvais régler le problème ou s'il existait une autre alternative ?

En vous remerciant.  

Mathilde Serrot

**Comment by seinecle** [comment]
Bonjour,

Compte tenu du temps assez court je vous suggère:

1. d'utiliser l'ordi d'une personne qui a une version de NetBeans qui fonctionne (à priori, près de 500 personnes à l'école)

2. passer aux tutoriels du lundi 26 Mars 2018. Celui de midi sera sans doute plein, en revanche celui du soir est toujours vide alors que nous avons 6 tuteurs et moi à votre disposition.

3. Poster ici les messages d'erreurs que vous obtenez et obtenir de l'aide pas à pas.

**Comment by MathildeSe** [comment]
Bonjour,

A cause de problèmes de connexion Internet je vous réponds un peu tardivement. 
J'utiliserai donc bien l'ordinateur de quelqu'un d'autre. Cependant je ne suis pas sûre de pouvoir venir lundi soir car je travaille dans un collège à Bellecour jusqu'à 18h30...



Envoyé depuis IBM Verse


   Clement Levallois --- Re: [seinecle/codapps] Non fonctionnement de Net Beans (#103) --- 
    De :"Clement Levallois" <notifications@github.com>A :"seinecle/codapps" <codapps@noreply.github.com>Cc :"MathildeSe" <mathilde.serrot@edu.emlyon.com>, "Author" <author@noreply.github.com>Date :mar., 20 mars 2018 21:07Objet :Re: [seinecle/codapps] Non fonctionnement de Net Beans (#103)
  
  Bonjour, 
 Compte tenu du temps assez court je vous suggère:   
 d'utiliser l'ordi d'une personne qui a une version de NetBeans qui fonctionne (à priori, près de 500 personnes à l'école)   
 passer aux tutoriels du lundi 26 Mars 2018. Celui de midi sera sans doute plein, en revanche celui du soir est toujours vide alors que nous avons 6 tuteurs et moi à votre disposition.   
 Poster ici les messages d'erreurs que vous obtenez et obtenir de l'aide pas à pas.
