### ISSUE TITLE
"illegal character"

### ISSUE THREAD

**Issue by simon-alexandre** [seinecle/codapps#104]
Bonjour à tous! 

J'ai un problème avec les accolades mettant fin au passage qui programme le bouton Farm. Le programme me refuse ces accolades, bien qu'elles soient dans le tutoriel, en me signalant "illegal character". Toutes les signes de code suivantes sont aussi considérées comme erronées. Vous savez comment faire?

**Comment by seinecle** [comment]
Pouvez vous poster votre code ici et pointer où se situe l'erreur svp?

**Comment by simon-alexandre** [comment]
Bonjour, 
Je vous joins une capture d'écran des lignes de code où l'erreur apparaît.
![capture d ecran 2274](https://user-images.githubusercontent.com/35851877/37864012-a7129246-2f68-11e8-9914-b83ded5ecdeb.png)

**Comment by simon-alexandre** [comment]
Bonjour,avez-vous trouvé l'erreur sur les lignes de code que je vous ai envoyées par capture d'écran?Cordialement Alexandre Simon-----Clement Levallois <notifications@github.com> wrote: -----To: seinecle/codapps <codapps@noreply.github.com>From: Clement Levallois <notifications@github.com>Date: 03/21/2018 02:24PMCc: simon-alexandre <alexandre.simon@edu.emlyon.com>, Author <author@noreply.github.com>Subject: Re: [seinecle/codapps] "illegal character" (#104)Pouvez vous poster votre code ici et pointer où se situe l'erreur svp?

**Comment by seinecle** [comment]
Bonsoir,
La copie d'écran ne montre qu'une vue très partielle. Pouvez-vous poster tout le code (pas en copie d'écran mais en copier-coller)? Vous pouvez aussi passer en tutoriel demain lundi.
Vérifiez bien votre code: je soupçonne qu'il s'agit d'un point virgule manquant, ou d'une accolade fermante de trop... qqch dans ce goût-là.

**Comment by simon-alexandre** [comment]
Bonjour,j'ai retapé tout à l'heure le code et il fonctionne. Il devait en effet d'agir d'une petite erreur. Je vous remercie de votre suivi.CordialementAlexandre Simon-----Clement Levallois <notifications@github.com> wrote: -----To: seinecle/codapps <codapps@noreply.github.com>From: Clement Levallois <notifications@github.com>Date: 03/25/2018 09:42PMCc: simon-alexandre <alexandre.simon@edu.emlyon.com>, Author <author@noreply.github.com>Subject: Re: [seinecle/codapps] "illegal character" (#104)Bonsoir,
La copie d'écran ne montre qu'une vue très partielle. Pouvez-vous poster tout le code (pas en copie d'écran mais en copier-coller)? Vous pouvez aussi passer en tutoriel demain lundi.
Vérifiez bien votre code: je soupçonne qu'il s'agit d'un point virgule manquant, ou d'une accolade fermante de trop... qqch dans ce goût-là.
