### ISSUE TITLE
App not scrollable in andriod

### ISSUE THREAD

**Issue by Thuski8** [seinecle/codapps#105]
After I sent the app in android phone, the end component is either cut off or missing. Why cant we scroll? I see the GUI builder and the scrollable Y option is ticked. How to deal with this type of issue? Cant we make the app with many components on the same screen and make it scrollable? Can you help me here?

**Comment by seinecle** [comment]
Hi,
Yes this is possible to have many components and make the screen scrollable to see them. This question is not in the scope of what can be handled in this Q&A and I invite you to post the question on the forum of Codename One, [here](https://groups.google.com/forum/#!forum/codenameone-discussions).
