### ISSUE TITLE
Problème d'affichage de l'appli 

### ISSUE THREAD

**Issue by maximedpt14** [seinecle/codapps#106]
Bonjour, 
après avoir effectué la première partie du module 6, mon appli ne change pas et s'affiche ainsi alors que j'ai effectué chacune des étapes demandées. Voici mon script : 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PushandPlay.myapp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image; 
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

/**
 *
 * @author maximechb
 */
public class PPform extends com.codename1.ui.Form {

Resources theme; 
 
 
  
   public PPform() {
       
       Resources theme = Resources.getGlobalResources();
  Image farmPic = theme.getImage("farm_50x37.png");
  Image clickPic = theme.getImage("click_50x64.png");
  Image cookiePic = theme.getImage("cookie_200x200.png");
  Image cookiestarPic = theme.getImage("cookie_200x200_star.png");
  
GridLayout gridLayoutThreeByOne = new GridLayout(3, 1);
this.setLayout(gridLayoutThreeByOne); 
this.setScrollable(false); 

Container northRegion = new Container();
BorderLayout borderLayoutNorth = new BorderLayout();
northRegion.setLayout(borderLayoutNorth);
Container centerRegion = new Container();
GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
centerRegion.setLayout(gridLayoutFourByOne);
centerRegion.setScrollableY(true);
Container southRegion = new Container();
BorderLayout blSouth = new BorderLayout();
southRegion.setLayout(blSouth);

this.addComponent(northRegion);
this.addComponent(centerRegion);
this.addComponent(southRegion);

ScaleImageButton cookie = new ScaleImageButton(); 
cookie.setIcon(cookiePic); 
cookie.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
cookie.getPressedStyle().setBgImage(cookiePic);
Label scoreLabel = new Label();
scoreLabel.setText("0 cookies");
scoreLabel.getStyle().setAlignment(Component.CENTER);  
Label cookiesPerSecondLabel = new Label();
cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER); 
northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookie);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel); 

   MultiButton autoclickButton = new MultiButton("Auto click"); 
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\""); 
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");
    MultiButton cookiestarButton = new MultiButton("Grandma");
cookiestarButton.setIcon(cookiestarPic); 
cookiestarButton.setTextLine2("\"Bake cookies with love\"");
cookiestarButton.setTextLine3("each grandma produces 1 cookie per second");
cookiestarButton.setTextLine4("price: 100 cookies. Owned: 0");
   MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

centerRegion.add(autoclickButton);
centerRegion.add(cookiestarButton);
centerRegion.add(farmButton);
   } 
}

<img width="184" alt="capture d ecran 2018-03-22 a 14 40 41" src="https://user-images.githubusercontent.com/35683758/37773877-0df58094-2ddf-11e8-8f67-ec84daab899b.png">

**Comment by seinecle** [comment]
Bonjour,
Il faut changer qq lignes dans le fichier `MyApplication.java`.
Voir ma réponse détaillée à [cette question](https://github.com/seinecle/codapps/issues/25).

**Comment by maximedpt14** [comment]
Bonjour Monsieur, 
Veuillez m’excuser mais lorsque je clique sur le lien joint à « cette question », cela ne fonctionne pas 
Cordialement 
Maxime Chabassier

**Comment by seinecle** [comment]
Le lien devrait marcher maintenant?

**Comment by maximedpt14** [comment]
Tout à fait, mais les bonnes lignes s'affichent dans myapplicationjava. cependant je viens de m'apercevoir qu'il y avait des ampoules jaunes sur ces lignes la. le problème réside peut être dans cette erreur ? 
<img width="779" alt="capture d ecran 2018-03-24 a 17 17 55" src="https://user-images.githubusercontent.com/35683758/37866197-7f54667a-2f87-11e8-92f4-ee8e39fe92c4.png">

**Comment by seinecle** [comment]
Non cela n'a pas de rapport.
