### ISSUE TITLE
Mettre application sur téléphone Android

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#107]
Bonsoir,
 
J'ai essayé de mettre l'application sur un téléphone android mais cela ne marche pas. J'ai scanné le QR code mais cela ne propose pas de télécharger l'application...

Merci de votre aide

**Comment by seinecle** [comment]
Cela devrait: une fois le scan fait, vous avez peut-être tapé sur un mauvais bouton. Il faut ouvrir l'url, et cela déclenche le téléchargement de l'app. C'est peut-être cette étape, qui peut se passer "en arrière plan" de votre téléphone, que vous n'avez pas vue. Passez en tutoriel ce lundi pour voir.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
