### ISSUE TITLE
Faut-il commencer une nouvelle app pour module 5?

### ISSUE THREAD

**Issue by CharlotteCarteret** [seinecle/codapps#108]
![2018-03-24](https://user-images.githubusercontent.com/35915909/37866917-40d384b2-2f91-11e8-8e23-7041d03b3e6e.png)
Bonjour,

 j'essaie de mettre mon application sur android comme expliqué au module 4 mais quand j'ouvre netbeans je n'ai plus rien comme vous pouvez le voir ci joint.
Comment cela se fait il d'après vous?
Est ce que ce module est important ou je peux passer au module 5? Enfin je me souviens en tutorat que vous m'aviez dit qu'après l'assignement 1 nous recommencions une nouvelle appli, un truc nouveau avec du codage...

Merci de m'éclairer sur comment je dois continuer!
Bon week end

Charlotte

**Comment by seinecle** [comment]
Effectivement vous pouvez passer au Module 5. Il est temps de le faire il ne reste que qq jours avant l'assignment.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
