### ISSUE TITLE
Message d'erreur sur la dernière étape du module 7

### ISSUE THREAD

**Issue by Thibzbrg** [seinecle/codapps#109]
Bonjour Monsieur j'ai suivi attentivement les instructions de ce module mais il semblerait que mes dernières lignes de codes empêchent le bon fonctionnement de l’application. Elles sont à l'origine d'un message d'erreur... Pouvez-vous m'expliquer ce que je dois faire pour résoudre cela svp ? 
Merci d'avance,
Thibault Brangolo

![image](https://user-images.githubusercontent.com/36760665/37876999-bb14031e-3054-11e8-8858-4364781deea8.png)

**Comment by seinecle** [comment]
Oui en effet il semble que:

- votre ligne 208 soit déjà écrite plus haut dans votre fichier: comme une variable ne peut être définie qu'une seule fois avec le même nom, cela bug.
- idem pour votre fonction `animate()`: elle est déjà écrite plus haut, d'où un bug.
- je vois aussi que vous avez fait une fausse manip et que vous avez créé un fichier `cookiesPerSecondLabel.java`: supprimez-le.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
