### ISSUE TITLE
Problème pour créer un écran 

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#11]
Bonjour, 
Je crois avoir un problème pour créer le "Screen1", des signes rouges se mettent à gauche des lignes de code...
Merci de votre aide

![probleme codding app](https://user-images.githubusercontent.com/35694045/35568589-d48dadfa-05c9-11e8-8515-4bc0a253a120.png)

**Comment by seinecle** [comment]
C'est en raison d'une accolade fermante `}` qui s'est rajoutée en ligne 40. Il faut la supprimer et tout devrait rentrer dans l'ordre.

Il faudra bien supprimer les lignes 41, 42 et 43 également: elles créent un nouveau Form et l'affichent à l'écran, il va donc cacher le `Screen1` que vous créez juste au-dessus en lignes 36 à 38.

**Comment by Clemencegiry** [comment]
Merci de votre réponse, je crois que cela fonctionne maintenant.
