### ISSUE TITLE
Problème affichage score

### ISSUE THREAD

**Issue by maximedpt14** [seinecle/codapps#110]
Bonjour, 
Suite à l'insertion des lignes concernant score dans netbeans, cela fausse tout le script et je ne peux plus afficher mon application. que faire ?
<img width="513" alt="capture d ecran 2018-03-25 a 17 48 42" src="https://user-images.githubusercontent.com/35683758/37877004-c8c4b2ce-3054-11e8-8cfe-651fee6fa3bf.png">

**Comment by seinecle** [comment]
Pouvez vous poster tout le code, pas en copie d'écran mais en copier coller du texte svp? Merci!

**Comment by maximedpt14** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cookieclicker;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

/**
 *
 * @author maximechb
 */
public class Form1 extends com.codename1.ui.Form {
    
     public Form1() {
  Resources theme = Resources.getGlobalResources();
  float score = 0f;
  
  
  Image grandmaPic = theme.getImage("grandma_50x50.png"); 
  Image farmPic = theme.getImage("farm_50x37.png");
  Image clickPic = theme.getImage("click_50x64.png");
  Image cookieCentraPic = theme.getImage("cookie_200x200.png");
  Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
  Label scoreLabel = new Label();
  Label cookiesPerSecondLabel = new Label();
  
  
  GridLayout gridLayoutThreeByOne = new GridLayout(3, 1); 
this.setLayout(gridLayoutThreeByOne); 

this.setScrollable(false);  

Container northRegion = new Container();
BorderLayout borderLayoutNorth = new BorderLayout();
northRegion.setLayout(borderLayoutNorth);
Container centerRegion = new Container();
GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
centerRegion.setLayout(gridLayoutFourByOne);
centerRegion.setScrollableY(true);
Container southRegion = new Container();
BorderLayout blSouth = new BorderLayout();
southRegion.setLayout(blSouth);

this.addComponent(northRegion);
this.addComponent(centerRegion);
this.addComponent(southRegion);

ScaleImageButton cookieCentral = new ScaleImageButton(); 
cookieCentral.setIcon(cookieCentraPic); 
cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
cookieCentral.getPressedStyle().setBgImage(cookiePressedPic); 


scoreLabel.setText("0 cookies");
scoreLabel.getStyle().setAlignment(Component.CENTER); 
cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);

northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

MultiButton autoclickButton = new MultiButton("Auto click"); 
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\""); 
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");

MultiButton grandmaButton = new MultiButton("Grandma");
grandmaButton.setIcon(grandmaPic); 
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
centerRegion.add(farmButton);
cookieCentral.addActionListener(
                (event) -> { 
                  score = score + 1;
                  scoreLabel.setText(score + " cookies");
}

}

**Comment by seinecle** [comment]
Ok:
il faut "sortir" votre variable `float score = 0f;` de la méthode constructeur où elle se trouve pour l'instant, et l'écrire plutôt juste avant. Cela donne un début de fichier comme ceci (rien n'a changé par rapport au vôtre, si ce n'est l'emplacement de `float score = 0f;`):

```
/*

    To change this license header, choose License Headers in Project Properties.
    To change this template file, choose Tools | Templates
    and open the template in the editor.
    */
    package cookieclicker;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

/**
*

    @author maximechb
    */
    public class Form1 extends com.codename1.ui.Form {

    float score = 0f;

    public Form1() {
    Resources theme = Resources.getGlobalResources();

Image grandmaPic = theme.getImage("grandma_50x50.png");
Image farmPic = theme.getImage("farm_50x37.png");
Image clickPic = theme.getImage("click_50x64.png");
Image cookieCentraPic = theme.getImage("cookie_200x200.png");
Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
Label scoreLabel = new Label();
Label cookiesPerSecondLabel = new Label();


```

**Comment by maximedpt14** [comment]
Merci beaucoup, cela fonctionne ! 👍

**Comment by maximedpt14** [comment]
Mais les accolades de la fin restent toujours soulignées en rouge, est-ce normal?

**Comment by seinecle** [comment]
Non... je me mets offline, passez au tuto demain pour la suite de l'aide!
