### ISSUE TITLE
Erreur de code empêche l'ouverture de l'app: "java.lang.IllegalArgumentException: Component is already contained in Container"

### ISSUE THREAD

**Issue by camillemrnt** [seinecle/codapps#111]
J'ai tapé tous les codes, et quand je lance java l'appli va se lancer puis se referme , je me demande si ce n'est pas mon ordinateur ...
<img width="2" alt="capture d ecran 2018-03-26 a 14 23 35" src="https://user-images.githubusercontent.com/36190228/37906441-666deb64-3102-11e8-9f4e-6839de58a758.png">
<img width="21" alt="capture d ecran 2018-03-26 a 14 24 06" src="https://user-images.githubusercontent.com/36190228/37906443-67b419d0-3102-11e8-8ca5-1b5862bad011.png">
<img width="854" alt="capture d ecran 2018-03-26 a 14 24 23" src="https://user-images.githubusercontent.com/36190228/37906450-6b203f5e-3102-11e8-9901-fb9cf46bdd8d.png">
<img width="827" alt="capture d ecran 2018-03-26 a 14 24 28" src="https://user-images.githubusercontent.com/36190228/37906454-6ec54e42-3102-11e8-8234-448ff552a324.png">
<img width="995" alt="capture d ecran 2018-03-26 a 14 24 32" src="https://user-images.githubusercontent.com/36190228/37906456-71932fa4-3102-11e8-98af-f1b60bff0a87.png">
<img width="995" alt="capture d ecran 2018-03-26 a 14 24 32" src="https://user-images.githubusercontent.com/36190228/37906458-7567b460-3102-11e8-8f9d-3af01d224b17.png">
<img width="805" alt="capture d ecran 2018-03-26 a 14 24 39" src="https://user-images.githubusercontent.com/36190228/37906461-79e88b36-3102-11e8-8542-e9856c9ec8aa.png">
<img width="900" alt="capture d ecran 2018-03-26 a 14 24 44" src="https://user-images.githubusercontent.com/36190228/37906463-7c17d04c-3102-11e8-90f2-c86c9b920c64.png">
<img width="622" alt="capture d ecran 2018-03-26 a 14 24 49" src="https://user-images.githubusercontent.com/36190228/37906464-7eb27500-3102-11e8-9ce5-3fcfd16b369f.png">

**Comment by camillemrnt** [comment]
merci d'avance

**Comment by seinecle** [comment]
Bonjour,

Plutôt que des copies d'écran pourriez vous poster le message complet d'erreur svp?

**Comment by camillemrnt** [comment]
voila le message d'erreur :
ant -f "/Users/camillemartin/NetBeansProjects/Cookie Clicker" -Dnb.internal.action.name=run run
No GUI Entries available
init:
Deleting: /Users/camillemartin/NetBeansProjects/Cookie Clicker/build/built-jar.properties
deps-jar:
Updating property file: /Users/camillemartin/NetBeansProjects/Cookie Clicker/build/built-jar.properties
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
compile:
run:
java.lang.IllegalArgumentException: Component is already contained in Container: Container[x=0 y=0 width=0 height=0 name=null, layout = BorderLayout, scrollableX = false, scrollableY = false, components = [Label, ScaleImageButton]]
	at com.codename1.ui.Container.insertComponentAtImpl(Container.java:717)
	at com.codename1.ui.Container.insertComponentAt(Container.java:708)
	at com.codename1.ui.Container.addComponent(Container.java:652)
	at com.codename1.ui.Container.add(Container.java:281)
	at com.openmailbox.camillemartin.myapp.Form1.<init>(Form1.java:62)
	at com.openmailbox.camillemartin.myapp.MyApplication.start(MyApplication.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:123)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1116)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:911)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Java Result: 1
BUILD SUCCESSFUL (total time: 9 seconds)

**Comment by seinecle** [comment]
Bonjour,
Il semble qu'à la ligne 62 de votre code, vous ajoutiez un Component à Form1, hors vous aviez déjà une ligne plus haut dans votre code faisant la même opération. C'est la source de l'erreur.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
