### ISSUE TITLE
Erreur "Le type d'élément "target" doit se terminer par la balise de fin correspondante ""

### ISSUE THREAD

**Issue by hortensedenicolay** [seinecle/codapps#112]
Bonjour 
Ce message apparait et m’empêche de continuer 
/Users/hortense/NetBeansProjects/RugbyApp/build.xml:52: Le type d'élément "target" doit se terminer par la balise de fin correspondante "</target>"

Mais je ne comprend pas  quelle target je dois changer 

Merci

**Comment by seinecle** [comment]
Bonjour,
- à quel moment ce message se déclenche-t-il?
- pouvez vous copier-coller le texte de l'erreur (pas une copie d'écran)

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
