### ISSUE TITLE
Pourquoi ne voit-on pas tous les "outils" (grandma, farm...) sur l'écrand de l'app

### ISSUE THREAD

**Issue by Chlodp** [seinecle/codapps#113]
Bonjour Monsieur, 
Lorsque j'ouvre mon application sur NetBeans je n'ai pas la totalité des options qui s'affiche sur le même écran, je dois descendre avec la souris pour que les options du style grandmas s'affichent. 

Lors du Tutorat, on m'avait conseillé de réintroduire 2 éléments au dessus car sans cela mon application ne fonctionnait pas alors que tout le texte était correct, est ce à cause de cela ? 

![screen shot 2018-03-28 at 9 06 15 am](https://user-images.githubusercontent.com/36769063/38014026-7a2b122e-3267-11e8-888f-dcc120e7ff49.png)
![screen shot 2018-03-28 at 9 06 06 am](https://user-images.githubusercontent.com/36769063/38014027-7a405d78-3267-11e8-93cb-5418d66a9daf.png)
![screen shot 2018-03-28 at 9 06 21 am](https://user-images.githubusercontent.com/36769063/38014031-7da30baa-3267-11e8-8033-34f677f56c9c.png)

Voici ce que j'ai dans la Form : 
package com.gmail.chloedepalmas;

import com.codename1.ui.util.Resources;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Image; 
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
/**
 *
 * @author mac
*/
public class Form3 extends com.codename1.ui.Form {
 Resources theme = Resources.getGlobalResources();
    private Object current;
    float score = 0f; 
    Parameters myParameters = new Parameters();
    Label cookiesPerSecondLabel = new Label();
    Label scoreLabel = new Label();
 
 public Form3() {
 registerAnimated(this);
 theme= Resources.getGlobalResources();
 
  Image grandmaPic = theme.getImage("grandma_50x50.png");
  Image farmPic = theme.getImage("farm_50x37.png");
  Image clickPic = theme.getImage("click_50x64.png");
  Image cookieCentraPic = theme.getImage("cookie_200x200.png");
  Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
  
GridLayout gridLayoutThreeByOne = new GridLayout(3, 1);
this.setLayout(gridLayoutThreeByOne);

this.setScrollable(false);

Container northRegion = new Container();

BorderLayout borderLayoutNorth = new BorderLayout();
northRegion.setLayout(borderLayoutNorth);

Container centerRegion = new Container();

GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
centerRegion.setLayout(gridLayoutFourByOne);
centerRegion.setScrollableY(true);

Container southRegion = new Container();

BorderLayout blSouth = new BorderLayout();
southRegion.setLayout(blSouth);

this.addComponent(northRegion);
this.addComponent(centerRegion);
this.addComponent(southRegion);

ScaleImageButton cookieCentral = new ScaleImageButton(); 
cookieCentral.setIcon(cookieCentraPic); 
cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
cookieCentral.getPressedStyle().setBgImage(cookiePressedPic); 

scoreLabel.setText("0 cookies");
scoreLabel.getStyle().setAlignment(Component.CENTER);

cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);

northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

MultiButton autoclickButton = new MultiButton("Auto click"); 
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\""); 
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");

MultiButton grandmaButton = new MultiButton("Grandma");
grandmaButton.setIcon(grandmaPic); 
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
centerRegion.add(farmButton);

cookieCentral.addActionListener(  
                (event) -> {
                    score = score + 1;
                    scoreLabel.setText(score + " cookies"); }  
        ); 
autoclickButton.addActionListener( 
        (event) -> {
            if (score >= myParameters.autoclickPrice) {
                myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                score = score - myParameters.autoclickPrice;
                myParameters.autoclickProd = myParameters.autoclickProd * myParameters.rateIncreaseProd;
                myParameters.autoclickPrice = myParameters.autoclickPrice * myParameters.rateIncreasePrice;
                autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice + " cookies. Owned: " + myParameters.autoclickOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
); 

grandmaButton.addActionListener(
        (event) -> {
            if (score >= myParameters.grandmaPrice) {
                myParameters.grandmaOwned = myParameters.grandmaOwned + 1;
                score = score - myParameters.grandmaPrice;
                myParameters.grandmaProd = myParameters.grandmaProd * myParameters.rateIncreaseProd;
                myParameters.grandmaPrice = myParameters.grandmaPrice * myParameters.rateIncreasePrice;
                grandmaButton.setTextLine4("price: " + myParameters.grandmaPrice + " cookies. Owned: " + myParameters.grandmaOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
);

farmButton.addActionListener(
        (event) -> {
            if (score >= myParameters.farmPrice) {
                myParameters.farmOwned = myParameters.farmOwned + 1;
                score = score - myParameters.farmPrice;
                myParameters.farmProd = myParameters.farmProd * myParameters.rateIncreaseProd;
                myParameters.farmPrice = myParameters.farmPrice * myParameters.rateIncreasePrice;
                farmButton.setTextLine4("price: " + myParameters.farmPrice + " cookies. Owned: " + myParameters.farmOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
);
}
 
long lastAnimatedTime;

@Override
public boolean animate() {
    if (System.currentTimeMillis() / 100 > lastAnimatedTime / 100) {
    computeScore();
    computeCookiesPerSecond(); 
    lastAnimatedTime = System.currentTimeMillis();
    return true;  
    } else {
        return false;  
    }
}

long lastTimeScoreWasComputed; 

private void computeScore() { 
    long currentTimeInSeconds = System.currentTimeMillis() / 1000; 
    long lastTimeScoreWasComputedInSeconds = lastTimeScoreWasComputed / 1000;  

    if (currentTimeInSeconds != lastTimeScoreWasComputedInSeconds) {  
        score = score + myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;  
        scoreLabel.setText(score + " cookies");  
        lastTimeScoreWasComputed = System.currentTimeMillis();  
    }
}
float cookiesPerSecond; 

private void computeCookiesPerSecond() {
    cookiesPerSecond =  myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;
    cookiesPerSecondLabel.setText(cookiesPerSecond + " cookies per second"); 
}
}

Ce que j'ai dans MyApplication : 
package com.gmail.chloedepalmas;

import static com.codename1.ui.CN.*;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Display;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.animations.CommonTransitions;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.UITimer;
import java.io.IOException;
import com.codename1.ui.Toolbar;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
        public void start() {
    if(current != null){
        current.show();
        return;
    }
    Form3 mainScreen = new Form3();
    mainScreen.show();
    }
    

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}

Ce que j'ai dans Parameters : 
package com.gmail.chloedepalmas;

/**
 *
 * @author mac
 */
public class Parameters {

float grandmaProd = 1f;
float grandmaPrice = 100f;
int grandmaOwned = 0;

float autoclickProd = 1f;
float autoclickPrice = 15f;
int autoclickOwned = 0;
float autoclickPeriod = 10f;

float farmProd = 3f;
float farmPrice = 500f;
int farmOwned = 0;

float rateIncreasePrice = 1.3f;
float rateIncreaseProd = 1.2f;

}

Bien cordialement

**Comment by seinecle** [comment]
Bonjour,
Ce n'est pas un bug, c'est un feature ;-)
Comme il y a beaucoup de choses à montrer à l'écran, on choisit de rendre scrollable la section centrale de l'écran (celle qui montre les outils que l'on peut acheter: auto-click, grandma et farm). C'est une solution possible, il y en aurait peut-être d'autre (rendre les boutons bcp plus petits par exemple?).

Cette fonction "la partie centrale de l'écran est scrollable" est obtenue grâce à la 3e ligne de code dan l'extrait suivant, tiré de votre code:

```
GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
centerRegion.setLayout(gridLayoutFourByOne);
centerRegion.setScrollableY(true);
```

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
