### ISSUE TITLE
dernière étape du module 6 - erreur sur un import

### ISSUE THREAD

**Issue by AudeJ** [seinecle/codapps#114]
Bonjour, 

Je rencontre des problèmes dans la dernière étape du module 6, 
Les trois dernières lignes à ajouter dans Form1 me font apparaître trois erreurs rouges et le lancement de mon app échoue (voir image ci-dessous), 

Sauriez-vous résoudre mon problème? 

Merci d'avance, 
Cordialement, 

Aude 

![image](https://user-images.githubusercontent.com/36734928/37982946-396f68d6-31f2-11e8-9a92-757e9cb38402.png)

**Comment by seinecle** [comment]
Bonjour,
La solution est de supprimer un fichier que vous avez créé par erreur: `MultiButton.java`

- supprimez-le en faisant un click droit sur ce fichier et sélectionnez "delete"
- dans votre fichier `Form1.java`, des icones d'erreur vont apparaître au niveau de "MultiButton". Résolvez la situation en cliquant sur l'icone d'erreur dans la marge et en sélectionnant "Add import..." (première ligne du menu proposé).

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
