### ISSUE TITLE
Run: preview n'affiche rien

### ISSUE THREAD

**Issue by PaulineRobinet** [seinecle/codapps#116]
Bonjour,

J'ai un problème car lorsque j'essaie d'afficher mon application, la fenêtre de preview s'ouvre bien mais n'affiche rien, et mon programme est toujours en mode run. néanmoins quand je referme la preview ça me met bien "build successful"

**Comment by seinecle** [comment]
Pouvez vous copier-coller le texte du message d'erreur qui s'affiche en bas (pas une copie d'écran)?

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
