### ISSUE TITLE
Project path can't contain spaces

### ISSUE THREAD

**Issue by Florentingueyraud** [seinecle/codapps#117]
Bonjour, 
J'ai un problème dès le départ: Quand j'essaie de créer un nouveau projet sur Netbeans, au moment de mettre de le nom de l'app, j'ai automatiquement un petit message rouge qui s'affiche "project path can't contain spaces". 

Ce message m'empêche de créer tout projet alors qu'il n'y a absolument aucun espace dans le nom que j'écris. 

J'ai eu beau relancer Netbeans une bonne dizaine de fois, le problème persiste...

Merci d'avance,
Florentin Gueyraud

**Comment by seinecle** [comment]
J'ai rencontré ce problème une fois également. Créez simplement votre projet, avec un nom sans espaces, dans un folder (un répertoire) de votre ordi qui ne contient d'espace ni dans son nom, ni dans le nom des répertoires dont il dépend.
(comme cela n'était pas pratique pour moi, après l'avoir créé, je l'avais ensuite déplacé dans le répertoire qui me plaisait - avec des espaces dans le nom de ce répertoire, et cela avait été possible).

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
