### ISSUE TITLE
Preview ne s'affiche pas

### ISSUE THREAD

**Issue by aureliaulr** [seinecle/codapps#118]
Bonjour monsieur, 

Après avoir entré l'intégralité des lignes de codes et lancé project run la fenêtre ne s'affiche pas et seul un message m'indiquant "build successful" apparait. Comment puis je faire pour régler ce problème ? 

Ci joint les lignes de code que j'ai rentrées : 

package com.gmail.aurelia.ulrapp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

public class Form1 extends com.codename1.ui.Form {
     Resources theme = Resources.getGlobalResources();
     Image farmPic = theme.getImage("farm_50x37.png");
     Image clickPic = theme.getImage("click_50x64.png");
     Image cookieCentraPic = theme.getImage("cookie_200x200.png");
     Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
     Image grandmaPic = theme.getImage("grandma_50x50.png");
     public Form1() {
         GridLayout gridLayoutThreeByOne = new GridLayout(3, 1); 
         this.setLayout(gridLayoutThreeByOne); 
         this.setScrollable(false);
         Container northRegion = new Container();
         BorderLayout borderLayoutNorth = new BorderLayout();
         northRegion.setLayout(borderLayoutNorth);
         Container centerRegion = new Container();
         GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
         centerRegion.setLayout(gridLayoutFourByOne);
         centerRegion.setScrollableY(true);
         Container southRegion = new Container();
         BorderLayout blSouth = new BorderLayout();
         southRegion.setLayout(blSouth);
         this.addComponent(northRegion);
         this.addComponent(centerRegion);
         this.addComponent(southRegion);
         ScaleImageButton cookieCentral = new ScaleImageButton(); 
         cookieCentral.setIcon(cookieCentraPic); 
         cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
         cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);
         Label scoreLabel = new Label();
         scoreLabel.setText("0 cookies");
         scoreLabel.getStyle().setAlignment(Component.CENTER);
         Label cookiesPerSecondLabel = new Label();
         cookiesPerSecondLabel.setText("0 per second");
         cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);
         northRegion.add(BorderLayout.NORTH, scoreLabel);
         northRegion.add(BorderLayout.CENTER, cookieCentral);
         northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);
         MultiButton autoclickButton = new MultiButton("Auto click"); 
         autoclickButton.setIcon(clickPic);
         autoclickButton.setTextLine2("\"Get your fingers some rest\""); 
         autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
         autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");
         MultiButton grandmaButton = new MultiButton("Grandma");
         grandmaButton.setIcon(grandmaPic); 
         grandmaButton.setTextLine2("\"Bake cookies with love\"");
         grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
         grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");
         MultiButton farmButton = new MultiButton("Farm");
         farmButton.setIcon(farmPic);
         farmButton.setTextLine2("\"Harvest cookies every summer!\"");
         farmButton.setTextLine3("each farm produces 3 cookies per second");
         farmButton.setTextLine4("price: 500 cookies. Owned: 0");
         centerRegion.add(autoclickButton);
         centerRegion.add(grandmaButton);
         centerRegion.add(farmButton);
   
      }
    
}

/**
 *
 * @author aurelia
 */

**Comment by seinecle** [comment]
il vous manque les lignes de code du module 7. Il faudrait également m'indiquer le message d'erreur éventuel.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
