### ISSUE TITLE
JSON Plugin

### ISSUE THREAD

**Issue by RandalFC** [seinecle/codapps#12]
Good day,  The github document doesn´t link the plugin since it is an image. Where should I download the JSON plugin from? I found a plugin from NetBeans called JSON Navigator. Should I install this plugin?

![image](https://user-images.githubusercontent.com/35812728/35577972-cbd50258-05b0-11e8-9436-ae52d00cf51e.png)

**Comment by RandalFC** [comment]
I found it here (http://www.java2s.com/Code/Jar/j/Downloadjavajsonjar.htm), followed the instructions on your pdf and it worked perfectly.

**Comment by RandalFC** [comment]
http://www.java2s.com/Code/Jar/j/Downloadjavajsonjar.htm

**Comment by seinecle** [comment]
Hi!

Codapps is evolving and the part of the course on building a messaging app is not supported anymore. The content on Coursera does not reflect it yet. The next version of the course can already be seen here (in progress):

https://seinecle.github.io/codapps/

Thanks for your interest!
