### ISSUE TITLE
Problème pour insérer un lien 

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#14]
Bonjour, 
Je n'arrive pas à insérer un lien dans l'application. Pourriez-vous m'aider? 
Merci!

![capture d ecran 2018-01-31 a 10 42 21](https://user-images.githubusercontent.com/35694045/35615831-9b31d4d2-0673-11e8-8bd1-35e0835a3005.png)

**Comment by seinecle** [comment]
Bonjour,

Voici une présentation du problème et sa solution. Est-ce que cela vous aide?

![Solving the issue][solution]

[solution]: https://docs.google.com/drawings/d/e/2PACX-1vTlzHx2Bau0nhXBJ-oOQ7Y98Uiw_xYQzwt7jdHB_lWtyDmEpEBYqxfr4Y0Ft9Y50DcBvSw5z708Drct/pub?w=1441&h=818 "Solution"

**Comment by Clemencegiry** [comment]
Bonjour, 

Cela semble avoir résolu une partie du problème mais cela ne marche toujours pas...

![capture d ecran 2018-02-01 a 10 10 29](https://user-images.githubusercontent.com/35694045/35670231-352a05b8-0738-11e8-9af1-18a668999168.png)

**Comment by seinecle** [comment]
Bonjour,
Le message d'erreur en rouge indique la ligne de code problématique: **c'est la ligne 59.**

Par défaut, cette ligne est cachée dans votre fichier pour ne pas encombrer la vue. Mais là on aimerait la voir. Pouvez vous cliquer sur la **petite croix à la hauteur de la ligne 32**? Cela va ouvrir les lignes de code cachées et vous pourrez voir la ligne 59. Faites une copie d'écran et mettez-là ici svp.

J'aurai également besoin de connaître le nom du bouton que vous avez créé dans le GUI Builder. Je suppose que c'est juste "Button", mais c'est pour être sûr. Vous pouvez voir le nom de votre Button ici:

![Solving the issue][solution]

[solution]: https://docs.google.com/drawings/d/e/2PACX-1vQ6EHoZNAiyh1KxQfbWROld16XdNH0AI1aApZfFCU_QuE3Gy-GZj1WwAkjGMJ1XZ_O558Xl7GxdARHM/pub?w=1441&h=819 "Solution"

**Comment by Clemencegiry** [comment]
Bonjour, 

Le bouton ne s'appelle pas Button mais "Button_1".
J'ai affiché la ligne 59 et voilà la capture d'écran: 

![capture d ecran 2018-02-02 a 13 16 09](https://user-images.githubusercontent.com/35694045/35732969-cc46b9da-081b-11e8-91ed-ebfd13c267d3.png)

Merci de votre aide

**Comment by seinecle** [comment]
Très bien merci! C'est clair.

Le code de la ligne 59 veut dire: "déclenche la fonction `onButton_1ActionEvent(ev)`"

Cette fonction n'existe pas dans votre code, bien qu'elle devrait bien être présente. Il y a une raison à cela mais passons directement à la solution:

Dans votre ligne 182, changez:

`public void onLinkActionEvent...`

par 

`public void onButton_1ActionEvent...`

Cela devrait suffire.

Par précaution, faites un click droit sur le nom de votre projet, et sélectionnez `clean and build` avant de relancer votre preview de l'app. `clean and build` oblige votre app à effacer des traces de codes antérieures.

Une question: je crois que le clic sur un bouton n'est pas décrit dans la version de mon cours que je donne cette année à emlyon. Comment avez vous accédé aux instructions? Aurais-je oublié de supprimer un ou deux docs sur Brightspace ou ailleurs? Merci!

**Comment by Clemencegiry** [comment]
Merci beaucoup, c'est bon cela fonctionne ! 
Pour ce qui est du bouton, j'ai tout trouvé sur github, il me semble que pour l'insertion d'un bouton c'était dans le module 2 "add text, pics, link..."

**Comment by seinecle** [comment]
Ravi que ca fonctionne!
(une partie du cours sur Github est obsolete, il vaut mieux ne se référer que à ce que vous trouvez sur https://seinecle.github.io/codapps/)
