### ISSUE TITLE
Problème avec l'installation 

### ISSUE THREAD

**Issue by Capucine2** [seinecle/codapps#15]
Bonjour, 
après avoir enregistré le fichier, je n'arrive pas à installer NetBeans sur mon ordinateur. En effet le processus d'installation se bloque et un message d'erreur apparait : "Warning : could not install some modules" avec le descriptif de tous les modules non installés... Que dois-je faire pour trouver une solution au problème?
Merci beaucoup

**Comment by seinecle** [comment]
Essayez de:

1. Désinstaller NetBeans
2. Effacez les fichiers qui sont dans :

* si vous avez un PC :

  * C:\Users\your_name\AppData\Local\NetBeans\Cache\8.1\
  *  C:\Users\your_name\AppData\Roaming\NetBeans\8.1\


* si vous avez un Mac :

  * /home/yourname/.cache/netbeans

3. Eteignez votre ordi et rallumez-le
4. Réinstallez NetBeans

([source](https://stackoverflow.com/questions/18545208/netbeans-could-not-install-some-modules))

**Comment by Capucine2** [comment]
Bonjour Monsieur, 
nous avions supprimé Netbeans de mon ordinateur ensemble lors du précédent tuto CODAPPS lundi dernier à 12h. Nous avions réinstallé Netbeans... Cependant je retombe sur le même message d'erreur suivant, je ne comprends pas pourquoi... que puis-je faire désormais car mon ordinateur refuse l'installation de Netbeans ? Je vous remercie pour votre aide...

Warning - could not install some modules: org.eclipse.equinox.common - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-equinox-common.jar: Cannot start org.eclipse.equinox.common state remains INSTALLED after start() org.eclipse.core.runtime.compatibility.auth - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-core-runtime-compatibility-auth.jar: Cannot start org.eclipse.core.runtime.compatibility.auth state remains INSTALLED after start() org.eclipse.core.jobs - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-core-jobs.jar: Cannot start org.eclipse.core.jobs state remains INSTALLED after start() org.eclipse.equinox.registry - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-equinox-registry.jar: Cannot start org.eclipse.equinox.registry state remains INSTALLED after start() org.eclipse.equinox.app - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-equinox-app.jar: Cannot start org.eclipse.equinox.app state remains INSTALLED after start() org.eclipse.equinox.preferences - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-equinox-preferences.jar: Cannot start org.eclipse.equinox.preferences state remains INSTALLED after start() org.eclipse.core.contenttype - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-core-contenttype.jar: Cannot start org.eclipse.core.contenttype state remains INSTALLED after start() org.eclipse.core.runtime - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-core-runtime.jar: Cannot start org.eclipse.core.runtime state remains INSTALLED after start() org.eclipse.equinox.security - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-equinox-security.jar: Cannot start org.eclipse.equinox.security state remains INSTALLED after start() org.eclipse.core.net - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-core-net.jar: Cannot start org.eclipse.core.net state remains INSTALLED after start() org.eclipse.mylyn.commons.core - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-mylyn-commons-core.jar: Cannot start org.eclipse.mylyn.commons.core state remains INSTALLED after start() org.eclipse.mylyn.commons.repositories.core - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-mylyn-commons-repositories-core.jar: Cannot start org.eclipse.mylyn.commons.repositories.core state remains INSTALLED after start() org.eclipse.mylyn.commons.net - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-mylyn-commons-net.jar: Cannot start org.eclipse.mylyn.commons.net state remains INSTALLED after start() org.eclipse.mylyn.commons.xmlrpc - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-mylyn-commons-xmlrpc.jar: Cannot start org.eclipse.mylyn.commons.xmlrpc state remains INSTALLED after start() org.eclipse.mylyn.tasks.core - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-mylyn-tasks-core.jar: Cannot start org.eclipse.mylyn.tasks.core state remains INSTALLED after start() org.eclipse.mylyn.bugzilla.core - org.netbeans.InvalidException: Netigso: C:\Program Files\NetBeans 8.2\ide\modules\org-eclipse-mylyn-bugzilla-core.jar: Cannot start org.eclipse.mylyn.bugzilla.core state remains INSTALLED after start()

**Comment by seinecle** [comment]
Nous devons régler ce problème lors d'un rv. Je vous envoie un email.

**Comment by seinecle** [comment]
@Capucine2  Je n'ai pas votre email - pouvez vous me joindre à levallois@em-lyon.com?

**Comment by Capucine2** [comment]
Merci beaucoup ! :)

**Comment by Capucine2** [comment]
Bonjour Monsieur, Voici mon mail ! je vous remercie pour votre aide, Capucine Colin de Verdière-----Clement Levallois <notifications@github.com> a écrit : -----A : seinecle/codapps <codapps@noreply.github.com>De : Clement Levallois <notifications@github.com>Date : 13/02/2018 11:28Cc: Capucine2 <capucine.colindeverdiere@edu.emlyon.com>, Mention <mention@noreply.github.com>Objet : Re: [seinecle/codapps] Problème avec l'installation (#15)@Capucine2  Je n'ai pas votre email - pouvez vous me joindre à levallois@em-lyon.com?
