### ISSUE TITLE
Aucune fenêtre "GUI builder" pour Form1

### ISSUE THREAD

**Issue by LouiseWbr** [seinecle/codapps#16]
Bonsoir,
Je ne parviens pas à ouvrir la fenêtre "GUI builder" que nous sommes supposés obtenir en cliquant-droit sur "Form1", c'est-à-dire lorsque j'ai cette fenêtre: 
![image](https://user-images.githubusercontent.com/36113672/35770897-a8418952-0924-11e8-89f2-b1c1cf976173.png)
Comment faire ?

Merci

**Comment by seinecle** [comment]
Bonsoir,

En suivant les étapes (clic droit sur le nom du projet, puis "new", etc...), quelle étape coince? Accédez-vous à la fenêtre qui vous demande quel nom donner à votre Form?

Par ailleurs, je vois que votre fenêtre au sein de NetBeans, qui devrait être à droite, n'est pas visible. Dans le menu, faites `Windows -> Editor` pour déclencher son affichage.

Ce problème, s'il n'est pas résolu, vous empêche d'avancer. Rendez vous aux tutoriels du lundi pour le régler plus rapidement!

**Comment by seinecle** [comment]
Problème résolu en tutoriel. Nous avons recommencé un nouveau projet, suivi les étapes des leçons 1 et 2 pas à pas, et le Form a pu être créé.
