### ISSUE TITLE
Création d'une app

### ISSUE THREAD

**Issue by ChloeMiguet** [seinecle/codapps#17]
Quand je veux vérifier que l'application que je viens de créer selon les consignes fonctionne en appuyant sur la flèche verte, un message d'erreur s'affiche...

**Comment by seinecle** [comment]
Ok! Pouvez vous mettre une copie d'écran où l'on voit bien le message d'erreur svp?

**Comment by ChloeMiguet** [comment]
[cid:272c2eb0-4507-44ca-8462-ee83e56ed73f]

________________________________
De : Clement Levallois <notifications@github.com>
Envoyé : lundi 5 février 2018 15:15:22
À : seinecle/codapps
Cc : ChloeMiguet; Author
Objet : Re: [seinecle/codapps] Création d'une app (#17)


Ok! Pouvez vous mettre une copie d'écran où l'on voit bien le message d'erreur svp?

**Comment by seinecle** [comment]
Pardon mais la copie d'écran n'a pas fonctionné

**Comment by seinecle** [comment]
Je vais clore cette issue. N'hésitez pas à la réouvrir si vous avez des éléments nouveaux à apporter.
