### ISSUE TITLE
Erreur dans le code empêche la preview de fonctionner

### ISSUE THREAD

**Issue by LouiseWbr** [seinecle/codapps#18]
Bonsoir,

- Je ne parviens plus à visualiser mon app: quand j'appuye sur le bouton vert type "play", rien n'apparaît sauf ce message d'erreur 
![image](https://user-images.githubusercontent.com/36113672/35817487-ca3367c2-0a9d-11e8-9c6d-5443ee9ce085.png)

Merci d'avance et bonne soirée !

**Comment by seinecle** [comment]
Bonsoir,

Par principe chaque issue évoque un problème différent, j'ai donc scindé votre issue en deux sous questions: celle-ci, et une autre que vous pouvez consulter [ici](https://github.com/seinecle/codapps/issues/21).

Sur celle-ci: il manque une accolade fermante `}` en ligne 44. Ajoutez-la: est-ce que tous les messages d'erreur dans la marge disparaissent ? (les icônes jaunes et rouges)

**Comment by LouisBrach** [comment]
Bonjour Monsieur, 
Je n'arrive pas non plus à lancer la preview parce que le logiciel ne "reconnaît" gui_Label et m'affiche un message d'erreur dans le "Output". 

Pouvez-vous m'aider s'il vous plaît ? 

Merci d'avance et bonne soirée !

![image](https://user-images.githubusercontent.com/35778830/36073412-62e2b78e-0f30-11e8-9d17-7e5545b91131.png)

**Comment by seinecle** [comment]
Voir issue #19 pour la résolution.
