### ISSUE TITLE
Problème pour la ligne "this.gui_Label.setText("pressed!");"

### ISSUE THREAD

**Issue by YanneBoisteault** [seinecle/codapps#19]
Bonjour, 

Je suis dans la partie où il faut créer un bouton afin de faire apparaître le texte "Press me!" mais une fois que je rentre la ligne "this.gui_Label.setText("pressed!");" sur Form1 dans NetBeans, un message d'erreur apparait et quand je clique sur la flèche verte pour lancer l'application cela ne fonctionne pas, l'application ne se lance pas. Que puis-je faire ? 

Cordialement, 
Yanne Boisteault

**Comment by seinecle** [comment]
Bonsoir,

Je pense que c'est le même cas de figure que cette question: #18 

Pouvez vous me le confirmer?

**Comment by LouisBrach** [comment]
Comme je l'ai commenté dans la question 18, ce n'est pas le même problème. Bien à vous, 
Louis Brach

**Comment by seinecle** [comment]
Bonjour,

Effectivement. [Cette étudiante avait un problème similaire](https://github.com/seinecle/codapps/issues/14#issuecomment-362547152), allez voir.

Vous devez:

- trouver le nom de votre `Label` dans le GUI Builder (sans doute Label_1, Label_2 ou équivalent)
- modifier la ligne de code pour bien mentionner le nom de votre `Label`: au lieu de `this.gui_Label` ce sera `this.gui_Label_1`.... si votre `Label` s'appelle `Label_1`, par exemple.

Est-ce que cela résout votre problème?

**Comment by LouisBrach** [comment]
Il s'appelle "Label" d'après les propriétés de Gui Builder, si j'ai bien compris 

![image](https://user-images.githubusercontent.com/35778830/36074638-3baa9f34-0f43-11e8-8049-b9fcd658b908.png)

**Comment by seinecle** [comment]
Oui... avez vous essayé de faire `clic droit` sur le nom du projet et sélectionner `clean and build`?

**Comment by LouisBrach** [comment]
Oui et cela me dit "Build failed".....

**Comment by seinecle** [comment]
Pouvez vous poster ici le code de votre fichier Form1? Faites juste un copier coller.

**Comment by LouisBrach** [comment]
Voilà : //-- DON'T EDIT ABOVE THIS LINE!!!
    public void onUpdateLabelTextCommand(com.codename1.ui.events.ActionEvent ev, com.codename1.ui.Command cmd) {
        this.gui_Label.setText("pressed!");
    }
}

**Comment by seinecle** [comment]
Je tenterais, dans cet ordre:

- d'effacer la Label dans le GUI Builder et de la recréer
- de créer un autre Form (en l'appelant Form2) en faisant attention de ne pas cocher "AutoLayout", puis de créer une Label dans ce Form.

Obtenez vous un meilleur résultat?

**Comment by LouiseWbr** [comment]
Bonjour,

Je rencontre le même problème de "preview", mais je doute que les causes soient les mêmes...
Pouvez-vous m'aider au vue de ce que le logiciel m'affiche ?
![image](https://user-images.githubusercontent.com/36113672/36143844-85ba468c-10ac-11e8-998a-e1b92663afe3.png)


Merci d'avance

**Comment by seinecle** [comment]
@LouiseWbr pouvez vous poster votre question dans une issue séparée svp?

**Comment by LouisBrach** [comment]
Rebonjour, 

Non, l'application ne veut même plus s'afficher à l'issue de la création de "Form2" 

![image](https://user-images.githubusercontent.com/35778830/36156836-8e34a290-10d8-11e8-8320-0d2f4898aac9.png)

**Comment by LouisBrach** [comment]
Autant recréer une application non ? 

Merci d'avance

**Comment by seinecle** [comment]
je ne vois pas tout le message d'erreur mais il me paraît cryptique. Effectivement, recréez plutôt une app.

**Comment by LouisBrach** [comment]
Bonjour Monsieur, 

Même après avoir recréer une application, j'ai toujours le même problème (je ne peux plus avancer avant la deadline de vendredi pouvez-vous m'aider à résoudre ce problème cryptique ?). J'ai pourtant suivi vos conseils et décocher ce qu'il fallait mais le preview refuse de s'afficher.... gui_Label n'est pas reconnu. 

![image](https://user-images.githubusercontent.com/35778830/36432590-d967e830-165a-11e8-9705-80f08906d2f2.png)

**Comment by seinecle** [comment]
Je vois une erreur: il y a un espace dans le "Name" que vous avez mis en créant l'action associée au bouton (la ligne 36 montre on `UpdateLabel Text`)

Malheureusement cette erreur est difficile à réparer, le plus simple est de recommencer une nouvelle app (désolé!)

Faites également attention à bien créer une Label, sinon votre bouton ne trouvera pas de Label dont il doit modifier le texte.

**Comment by LouisBrach** [comment]
C'était bien ça ! Merci
