### ISSUE TITLE
Plugin Codename One not Found in Plugin List

### ISSUE THREAD

**Issue by tristan-baraille** [seinecle/codapps#2]
Bonjour, 

Je viens d'installer NetBeans en suivant les instructions, en revanche impossible de trouver le plugin Codename One. Il n'apparaît ni dans la liste "Available plugin", ni dans "Installed". 

![plugin codename one](https://user-images.githubusercontent.com/35726197/35270246-d741f31c-002e-11e8-8783-62f0e2cef2ca.png)

Est-ce que j'ai fait une mauvaise manipulation pendant l'installation ?

**Comment by seinecle** [comment]
Merci pour le screenshot.

Deux possibilités:

* soit le serveur du plugin est [momentanément indisponible](http://codenameone.blogspot.fr/2018/01/meltdown-and-other-updates.html) 

* soit il y a une mauvaise configuration, c'est rare mais ca arrive. Essayez:

  * Dans cette même fenêtre, cliquez sur l'onglet "Settings".
  * Puis essayez de suivre les instructions de [la section 3 sur cette page](https://github.com/seinecle/codapps/blob/master/src/main/asciidoc/en/module-1/checking-for-plugin-updates.adoc).

**Comment by tristan-baraille** [comment]
Merci pour cette réponse, 

Je suis allé dans la partie settings, j'ai cliqué sur "Add" et ajouté manuellement Codename One en entrant le Name et l'URL indiqués. Un plugin est alors apparu dans ma liste "Available", je l'ai téléchargé.

![installation manuelle codename one](https://user-images.githubusercontent.com/35726197/35298258-de32851c-0081-11e8-8b59-fc9fc6229b5d.png)


Est-ce que c'est la bonne version ?

**Comment by seinecle** [comment]
Oui, c'est bon! Vous pouvez l'installer.

La version  disponible est toujours la plus récente. Ensuite, quand le plugin évoluera et qu'une nouvelle version sortira, vous aurez une notification dans NetBeans vous invitant à télécharger ce nouveau plugin. Toutes les étapes sont décrites dans la leçon que j'ai citée dans mon commentaire précédent.
