### ISSUE TITLE
Codename one n'apparait pas lorsque je veux créer un nouveau projet

### ISSUE THREAD

**Issue by BenjaminCharpin** [seinecle/codapps#20]
Bonjour,

J'avais déjà installé (sans problème) netbeans et le plugin codename one sur mon précédent PC mais j'en ai changé.
J'ai eu beau réessayer trois fois de réinstaller le plugin, l'option "codename one" n'apparait pas lorsque je veux créer un nouveau projet.

Merci d'avance

**Comment by seinecle** [comment]
Le plugin apparaît-il dans votre liste de plugins?
(voir le menu` Tools -> Plugins`, puis aller dans l'onglet `Installed`)

**Comment by BenjaminCharpin** [comment]
Non il n'apparaît pas. Pourtant à chaque tentative d'installation, un message disant que le plug-in a bien été installé et qu'il suffit de relancer Netbeans pour finaliser l'installation apparaît. Mais une fois Netbeans relancé, je reviens au point de départ, comme si je n'avais rien installé.

**Comment by BenjaminCharpin** [comment]
Problème résolu. Il suffisait de réinstaller Netbeans en vérifiant bien que ce soit la bonne version pour que le plugin s'installe correctement.
