### ISSUE TITLE
Activer un bouton

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#22]
Bonjour, 
Je n'arrive pas à mettre une action sur mon bouton, cela m'affiche un message d'erreur. 
Merci de votre aide

![capture d ecran 2018-02-08 a 19 30 42](https://user-images.githubusercontent.com/35694045/35991212-c52af0a4-0d06-11e8-8c1d-cc581dd108e4.png)

**Comment by seinecle** [comment]
Bonsoir,
Il semble manquer un point virgule à la fin de la ligne où les erreurs sont pointées.

**Comment by Clemencegiry** [comment]
En effet, merci !
