### ISSUE TITLE
Mode Autolayout activé pour le Form1

### ISSUE THREAD

**Issue by ghost** [seinecle/codapps#23]
J'ai surement dû garder le mode Autolayout en créant mon "Form1". Il m'est alors impossible de changer le layout.
Comment on peut enlever le mode Autolayout, sans supprimer le "Form1" ?
Merci.

**Comment by seinecle** [comment]
Cela n'est malheureusement pas possible :-(
Quand vous créerez un autre Form sans Auto Layout, veillez à lui donner un autre nom (Form2 par exemple) car lui donner le même nom que le précédent pourrait causer des problèmes.
