### ISSUE TITLE
Problème pour lancer l'application après avoir utilisé des containers

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#24]
Bonjour, 

J'ai essayé d'utiliser des containers pour la mise en page de l'écran et d'y ajouter des images comme expliqué dans le module. J'ai suivi les instructions mais quand j'essaye de démarrer l'application, celle-ci ne se lance pas...

Merci de votre aide

Bon dimanche

![capture d ecran 2018-02-11 a 11 19 11](https://user-images.githubusercontent.com/35694045/36072292-76285bcc-0f1d-11e8-8104-32ecd648f1c4.png)

**Comment by seinecle** [comment]
Bonjour,
Il y a sans doute un point-virgule `;` manquant à la fin d'une ligne de code , c'est ce que le message d'erreur indique.
Je ne peux pas le voir sur votre copie d'écran, il faudrait scroller vers le bas et afficher la ligne de code fautive.
Pouvez vous vérifier et poster une nouvelle copie d'écran si le problème persiste?

**Comment by Clemencegiry** [comment]
Bonsoir,
Je n'ai pas trouvé où il manquait un ";", à la fin de la ligne de code fautive il y a bien un ;


![Uploading Capture d’écran 2018-02-11 à 21.13.33.png…]()

**Comment by Clemencegiry** [comment]
Bonsoir,
Je n'ai pas trouvé où il manquait un ";", à la fin de la ligne de code fautive il y a bien un ;

![capture d ecran 2018-02-11 a 21 13 33](https://user-images.githubusercontent.com/35694045/36077925-dac5e470-0f70-11e8-9289-c23cbed8c36a.png)

**Comment by seinecle** [comment]
Erreur trouvée je crois: le nom de votre Container est "Vocabulary container", avec un espace. C'est cet espace qui casse le code. Les noms de Components ne doivent pas comporter d'espace. Faites la chose suivante:

- effacez la ligne de code 26 (la ligne en erreur)
- supprimer votre Container et créez-en un nouveau avec un nom sans espace
- faites clic droit sur le nom de votre projet et choisissez `clean and build`

**Comment by Clemencegiry** [comment]
Oui c'est bon le problème est résolu, merci beaucoup !
Bonne soirée
