### ISSUE TITLE
J'ai créé un Form mais quand je lance la preview c'est un autre écran qui s'affiche

### ISSUE THREAD

**Issue by kaisbelala** [seinecle/codapps#25]
Bonjour,

Après avoir ajouté un Label et un Button à l'aide du GUI Builder, je tente de les apercevoir en lançant la fonction "Run Project" sauf que les modifications ne sont pas prises en compte et l'aperçu reste le même quoi qu'il arrive : (j'ai bien sauvegardé les modifications via GUI Builder)

![capture d ecran 2018-02-11 a 17 19 04](https://user-images.githubusercontent.com/35892832/36075469-af6dc8f4-0f4f-11e8-9a9f-dbe739b0eb9b.png)

**Comment by kaisbelala** [comment]
En cliquant sur "Let's Get Started" je suis redirigé vers une page de tutoriels du site Codename

**Comment by seinecle** [comment]
Je vois ce qui se passe: regardez les instructions [de cette leçon](https://seinecle.github.io/codapps/generated-html/creating-a-form-two-methods.html), en particulier les instructions qui sont juste après la Figure 8.

**Comment by kaisbelala** [comment]
Merci. Le problème est à moitié réglé. D'après la leçon, dans MyApplication.java je suis censé retrouver ces lignes de code : 

public void start() {
    if(current != null){
        current.show();
        return;
    }
    Form hi = new Form("Hi World", BoxLayout.y());
    hi.add(new Label("Hi World"));
    hi.show();
}

Or je retrouve en réalité ces lignes qui sont légèrement différentes : 

public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));


Comment faire pour retrouver les lignes annoncées dans la leçon ?

**Comment by seinecle** [comment]
Vous ne les retrouverez pas car vous avez créé votre projet en vous trompant légèrement: vous avez pris `Get Started App` au lieu de `Hello World (Bare Bones)`.

Mais cela peut se rattraper. Faites comme ceci:

- supprimez la ligne `Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));`

- mettez à la place les lignes indiquées dans la leçon:

```
Form1 myForm1 = new Form1();
myForm1.show();
```

Faites bien attention à ne pas supprimer ou ajouter d'accolade fermante `}`

Est-ce que cela résout votre problème?

**Comment by kaisbelala** [comment]
Malheureusement cela ne résout pas le problème, le message "BUILD FAILED" s'affiche en bas après avoir tenté de lancer le simulateur. 

Je devrais peut être recréer un projet en prenant Hello World (Bare Bones) cette fois-ci ?

**Comment by seinecle** [comment]
Eventuellement. Je peux mieux comprendre la source du problème et vous aider si vous mettez ici une copie d'écran qui montre la ligne de code où une icone d'alerte rouge et jaune figure dans la marge.

**Comment by kaisbelala** [comment]
J'ai recommencé en prenant Hello World et le problème est résolu.

Merci pour votre aide !

**Comment by seinecle** [comment]
Bonne initiative! Bon courage pour la suite.
