### ISSUE TITLE
Deux projets sur un même ordinateur

### ISSUE THREAD

**Issue by maellebzd** [seinecle/codapps#26]
Bonjour, 
Je n'ai toujours pas réussi à installer le logociel sur mon ordinateur...
Je voulais savoir si je pouvais faire le travail demandé sur le logiciel d'un de mes camarades, ayant déjà bien avancé dans le module ou est ce que cela va entraver son travail?
Si je peux, est ce que je dois faire des manipulations différentes de la formation proposée?

merci d'avance

**Comment by seinecle** [comment]
Bonjour,
Vous pouvez tout à fait faire deux projets sur le même ordi (celui de votre camarade donc).
