### ISSUE TITLE
Ligne de code en erreur en raison d'espaces dans le nom d'un Component

### ISSUE THREAD

**Issue by LouiseWbr** [seinecle/codapps#27]
Bonjour,

Voilà ce qui est affiché quand j'essaye de preview l'app:
![image](https://user-images.githubusercontent.com/36113672/36145581-156ebec0-10b2-11e8-9ba2-def18ac71071.png)

Comment faire ?

Merci d'avance

**Comment by seinecle** [comment]
Bonjour,
Il semble qu'un `Button` ou autre Component a un `Name` qui comporte des espaces. Cela brise le code en ligne 62. Solution:

Recommencer une app et ne plus mettre d'espace dans les noms des Components

**Comment by seinecle** [comment]
Je vais clore cette issue. N'hésitez pas à la réouvrir si vous avez des éléments nouveaux à apporter.
