### ISSUE TITLE
Question sur placement des Components dans Container, et layouts

### ISSUE THREAD

**Issue by LouiseWbr** [seinecle/codapps#28]
Bonjour,

Est-ce bien le résultat attendu (liste de containers et leur contenu) quant aux consignes "In each of these Containers, add a ScaledLabel for the picture in Center position" puis "In each of these Containers, add a Label for the caption in South position" ?
![image](https://user-images.githubusercontent.com/36113672/36145997-5d1aac88-10b3-11e8-81c6-225016c5d063.png)

Merci d'avance

**Comment by seinecle** [comment]
J'essaie de voir... je crois que votre "Vocabulary Container" doit lui-même être en position centrale dans le Form? C'est à dire:

- le Form est en layout "Border"
- le Container "Vocabulary Container" doit être placé en "Center".

Là, sur votre copie d'écran, votre "Vocabulary Container" est coincé tout à droite, je pense qu'il est en position "East". Mettez le en "Center".

**Comment by seinecle** [comment]
Je vais clore cette issue. N'hésitez pas à la réouvrir si vous avez des éléments nouveaux à apporter.
