### ISSUE TITLE
Problème création compte

### ISSUE THREAD

**Issue by LouiseWbr** [seinecle/codapps#29]
Bonjour,

Voici le message qui apparaît quand je cherche à relier mon compte NetBeans au compte Codename.com 
![image](https://user-images.githubusercontent.com/36113672/36147353-310a6a84-10b8-11e8-9d2b-5f7b6cfab652.png)

Que faire ?

Merci d'avance

**Comment by seinecle** [comment]
Je pense que vous pouvez juste cliquer sur "Oui"
