### ISSUE TITLE
Access Denied Netbeans

### ISSUE THREAD

**Issue by LucilleTD** [seinecle/codapps#3]
Bonjour, 
J'ai installé NetBeans et le plugin CodeNameOne sans problème, cependant lorsque je tente de créer un nouveau projet comme indiqué dans les consignes du module 1, le message "access is denied" s'affiche. Y'a-t-il une solution ?
Merci

**Comment by seinecle** [comment]
Pouvez vous m'envoyer un screenshot de qui montre l'erreur?
A quelle moment exact se produit elle?

**Comment by LucilleTD** [comment]
Le problème survient lorsque je clique sur le bouton "Finish"
![screenshot](https://user-images.githubusercontent.com/35704546/35281203-9ff2606c-0052-11e8-9326-e6029b79b514.png)

**Comment by seinecle** [comment]
Merci!

Deux idées:

* Sur l'écran précédent, je me demande où vous enregistrez le projet. C'est peut-être dans un répertoire de votre ordi auquel vous n'avez pas accès?

* Avez-vous les droits d'administrateur sur votre ordi?

**Comment by LucilleTD** [comment]
J'ai vérifié et je possède bien les droits d'administrateur sur mon ordi et j'ai également essayé de changer le lieu d'enregistrement de mon projet mais le problème persiste.

**Comment by seinecle** [comment]
Merci. J'utilise Stackoverflow pour chercher de l'aide extérieure:

https://stackoverflow.com/questions/48407994/creation-of-new-project-fails-with-access-denied

**Comment by seinecle** [comment]
Je réalise juste maintenant que vous êtes sur Windows.

* Dans l'écran précédent où l'on vous demande où enregistrer votre projet, essayez de choisir un répertoire différent: créez un répertoire "codapps" dans "Mes Documents" par exemple et choisissez cet endroit pour votre projet. Puis postez une copie d'écran ici svp?

* La version de Java installée su votre ordinateur peut aussi être un souci. Si c'est Java 9 (la dernière version, cela peut être la cause du problème. Pour connaître la version de Java sur votre ordi:

    * Cliquez sur le bouton Démarrer
    * Faites défiler les applications et les programmes répertoriés jusqu'à ce que vous voyiez le dossier Java
    * Cliquez sur le dossier Java, puis sur A propos de Java pour voir la version de Java

**Comment by LucilleTD** [comment]
Merci beaucoup pour votre aide, j'ai finalement découvert que le problème provenait de mon anti-virus qui empêchait NetBeans et Java de procéder à des changements dans mes dossiers. Après modification des paramètres, j'ai donc réussi à créer un nouveau projet!

**Comment by seinecle** [comment]
Alléluia :-)
