### ISSUE TITLE
The Guibuilder window won't open 

### ISSUE THREAD

**Issue by paulinecasabianca** [seinecle/codapps#30]
Bonjour, 

J'essaie d'ourdir la fenêtre GuiBuilder mais ca ne marche pas. 
Voici une capture d'écran 
![capture d ecran 2018-02-14 a 10 55 15](https://user-images.githubusercontent.com/35935902/36197993-b57fb8f6-1175-11e8-9882-78abe2e7c55c.png)

Merci par avance

**Comment by seinecle** [comment]
Bonjour,
Il y a une alerte rouge sur chacun des deux fichiers "GuiComponent" et "Form1". Si vous essayez d'ouvrir "Form1", pouvez vous faire une copie d'écran des lignes de code de Form1, à la hauteur où une erreur est signalée par une icone rouge et jaune dans la marge?

**Comment by paulinecasabianca** [comment]
Bonjour, 
Merci pour votre réactivité. Voici la capture d'écran. 


![capture d ecran 2018-02-15 a 12 14 22](https://user-images.githubusercontent.com/35935902/36254074-fc1b2e74-1249-11e8-87b4-bedb048ca0ea.png)

![capture d ecran 2018-02-15 a 12 14 33](https://user-images.githubusercontent.com/35935902/36254083-ff2b41a8-1249-11e8-8690-1803cffa7c17.png)

**Comment by seinecle** [comment]
Je vois qu'il y a une `Scaled_Label` sur vote `Form1` (on la voit à la ligne 24), mais la ligne 58 parle de `this.gui_Label` (surligné en rouge par NetBeans pour signaler qu'il ne reconnaît pas cette variable): essayez de mettre à la place `this.gui_Scaled_Label` et ca devrait aller mieux

**Comment by paulinecasabianca** [comment]
J'ai essayé de modifier la ligne mais cela ne fonctionne toujours pas ... 
Lorsque je clique sur "play" ni form1 ni guicomponent ni myapplication ne s'ouvre ... 

![capture d ecran 2018-02-16 a 12 07 40](https://user-images.githubusercontent.com/35935902/36305016-21392440-1312-11e8-9550-db042cfec035.png)

**Comment by paulinecasabianca** [comment]
le symbole attention ne s'affiche que pour guicomponent, j'ai essayé de la supprimer mais cela ne marche pas, voici le message qui s'affiche 
![capture d ecran 2018-02-16 a 12 11 20](https://user-images.githubusercontent.com/35935902/36305103-85ca2666-1312-11e8-840e-2b41ff4ff14b.png)

**Comment by seinecle** [comment]
Bonjour,
Il y a une icône rouge à côté de votre fichier "GuiComponent.java", ce qui signale une erreur à corriger dans ce fichier. Pouvez vous l'ouvrir et poster une copie d'écran ici, à la hauteur où une erreur est signalée? Merci.

**Comment by paulinecasabianca** [comment]
Bonsoir, pour ma part je suis toujours bloquée... mais une amie qui le fait également sur mon ordinateur en est a l'étape finale, mais elle n'arrive pas a s'inscrire sur codenameone. Elle a bien reçu le mail de confirmation mais lorsqu'elle clique pour confirmer son adresse mail, il est écrit qu'elle doit installer de nombreux logiciels, est-ce nécessaire ? 

Merci beaucoup pour votre temps
![capture d ecran 2018-02-17 a 18 56 51](https://user-images.githubusercontent.com/35935902/36344039-ae794dd2-1414-11e8-868d-4b607b83a4e1.png)

**Comment by seinecle** [comment]
Bonjour,
Il faut créer une "issue" par question pour bien s'y retrouver. Je copie colle votre question dans une nouvelle issue #35 et je vous invite à consulter ma réponse sur cette nouvelle issue (#35).

**Comment by paulinecasabianca** [comment]
Bonjour, voici le screen de la ligne ou il y a l'erreur : 

![capture d ecran 2018-02-19 a 10 58 57](https://user-images.githubusercontent.com/35935902/36371963-e8b55676-1563-11e8-9aa8-109412741508.png)

**Comment by seinecle** [comment]
Bonjour,

Ok il y a dû y avoir un mauvais copier-coller. La ligne dit "Form1" mais votre fichier s'appelle `GuiComponent.java`

Pour régler ce problème:

- remplacez Form1 par GuiComponent à la ligne 9 et 10.
- je crois qu'il y aura encore une ligne plus bas dans le fichier qui mentionnera "Form1": remplacez également par GuiComponent

**Comment by paulinecasabianca** [comment]
Bonjour, 

Ca a marché, merci beaucoup pour votre temps.
