### ISSUE TITLE
Le fenêtre Guibuilder ne veut pas s'ouvrir 

### ISSUE THREAD

**Issue by paulinecasabianca** [seinecle/codapps#31]
Bonjour,

J'essaie d'ourdir la fenêtre GuiBuilder mais ca ne marche pas.
Voici une capture d'écran
![capture d ecran 2018-02-14 a 10 55 15](https://user-images.githubusercontent.com/35935902/36197993-b57fb8f6-1175-11e8-9882-78abe2e7c55c.png)

Merci d'avance

**Comment by seinecle** [comment]
Je vous réponds sur la question précédente.
