### ISSUE TITLE
Fond d'écran et photo

### ISSUE THREAD

**Issue by YanneBoisteault** [seinecle/codapps#32]
Bonjour, 

J'ai d'abord mis une photo par guibuilder, cela a fonctionné, ensuite j'ai mis un fond d'écran, cela a aussi fonctionné mais ma photo n'apparaît plus sur le fond d'écran alors qu'elle apparaît toujours dans guibuilder. Que puis-je faire pour résoudre ce problème svp ? 

Cordialement,
Yanne

**Comment by seinecle** [comment]
Bonjour,
Désolé pour cette réponse tardive cette question m'avait échappé. C'est un problème de layout, qui est difficile à diagnostiquer et résoudre à distance. Passez aux tutoriels du lundi pour recevoir une assistance.

**Comment by seinecle** [comment]
Bonjour, la dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
