### ISSUE TITLE
pas de preview

### ISSUE THREAD

**Issue by CelianeB** [seinecle/codapps#33]
Bonjour, 
j'ai suivi les instructions du module 2 mais lorsque j'essaie de créer mon application (après avoir choisi le thème et le template donnés), rien ne s'ouvre... aucune fenêtre, aucun écran de téléphone

Merci

**Comment by seinecle** [comment]
Pouvez vous poster une copie d'écran svp?

**Comment by CelianeB** [comment]
j'ai essayé de désinstaller Netbeans et de le réinstaller en attendant et maintenant l'installation ne veut pas se faire car "JDK 8 update 161 was not completed"... ça fait 3 fois que j'essaie, je ne comprends pas...

**Comment by seinecle** [comment]
Bonjour,
- si votre ordi est sous Windows
- et si l'erreur que vous mentionnez a un code d'erreur 1603

je vous conseille de suivre les étapes de cette vidéo:

https://www.youtube.com/watch?v=hv9aM47XaUs

**Comment by seinecle** [comment]
Le dernier échange de cette conversation date d'une semaine. Je clos cette "issue". Vous pourrez la réouvrir à tout moment si vous avez besoin d'assistance supplémentaire sur cette question précise. Si vous avez une question portant sur un sujet différent, ouvrez une nouvelle issue.
