### ISSUE TITLE
Les trois lignes de code à remplacer pour afficher le Form1 ne sont pas dans le fichier MyApplication.java

### ISSUE THREAD

**Issue by LouiseRzasa** [seinecle/codapps#34]
Bonjour, 

Au moment de passer de Gui Bilder à Netbeans, lorsqu'il faut changer les trois lignes en deux lignes ("_NewForm1 = ...._") je rencontre un problème. Les trois ligne à remplacer n'apparaissent pas telles qu'elles dans Netbeans et je n'arrive donc pas à insérer Form1 dans Netbeans. 

Merci de votre aide.

**Comment by seinecle** [comment]
Pouvez-vous mettre une copie d'écran svp?

**Comment by LouiseRzasa** [comment]
Voici ce que présente mon écran et les trois lignes qui n'apparaissent donc pas (pas telles qu'elles) 
![capture d ecran 2018-02-17 a 22 44 12](https://user-images.githubusercontent.com/36564530/36345918-a0500e6a-1434-11e8-8652-83c17f6b0c07.png)
![capture d ecran 2018-02-17 a 22 46 33](https://user-images.githubusercontent.com/36564530/36345920-a4786186-1434-11e8-966a-aea4dd267665.png)

**Comment by seinecle** [comment]
Bonjour,
Je pense que vous avez créé une app en mode "Get Started App", alors que le cours demande de créer une app "Hello World (Bare Bones)". Effacez cette app, et créez-en une nouvelle en suivant les instructions précisément pour bien retrouver les lignes de codes attendues.

(coder est une discipline bête et méchante de respect des consignes à la lettre... c'est fastidieux mais les résutats sont ensuite impressionnants! Courage!)

**Comment by seinecle** [comment]
Le dernier échange de cette conversation date d'une semaine. Je clos cette "issue". Vous pourrez la réouvrir à tout moment si vous avez besoin d'assistance supplémentaire sur cette question précise. Si vous avez une question portant sur un sujet différent, ouvrez une nouvelle issue.
