### ISSUE TITLE
Les layouts ne marchent pas

### ISSUE THREAD

**Issue by DenisLai** [seinecle/codapps#36]
Bonjour Monsieur,

Je travaille actuellement sur le module 3 et à l'étape 2, lorsque je veux tester les différents layouts, rien ne change et le message « auto layer mode currently on » s'affiche systématiquement (cf screenshot). 
Comment régler la situation ? Est-ce qu'il faut désactiver "l'auto layer mode" ? 

Merci d'avance
<img width="1280" alt="capture d ecran 2018-02-20 a 15 37 28" src="https://user-images.githubusercontent.com/36602114/36430022-732f7e3a-1654-11e8-8700-19165bb8d58c.png">

**Comment by seinecle** [comment]
Bonjour,
Vous avez créé le Form en laissant la case "AutoLayout" cochée. Vous devez créer un nouveau `Form` (Form2 par exemple) en prenant bien garde à décocher AutoLayout. Voir [cette partie de la leçon qui en parle](https://seinecle.github.io/codapps/generated-html/creating-a-form-two-methods.html#_2_another_possibility_creating_a_form_without_coding_with_the_gui).

**Comment by DenisLai** [comment]
Ça a marché, merci beaucoup.
