### ISSUE TITLE
Action "changer de texte"

### ISSUE THREAD

**Issue by leadebrincat** [seinecle/codapps#37]
Bonjour, 
Est-il possible de créer un bouton qui change le texte de ce bouton lorsque l'on clique dessus ? J'essaye depuis quelques jours mais la seule chose que j'arrive à faire c'est de changer le titre de mon Form1...

**Comment by seinecle** [comment]
C'est possible. Suivez les étapes de cette partie de la leçon sur la création d'un bouton et la création d'une action attachée au bouton ([ici](https://seinecle.github.io/codapps/generated-html/adding-labels-and-buttons.html#_c_step_by_step_creation_of_an_action_attached_to_the_button)).

Sauf que dans votre cas, vous voulez changer le texte du bouton lui-même, pas le texte de la Label. Très bien, mettez juste le nom du bouton au lieu du nom de la label! Le résultat doit ressembler à ca:

```
public void onButtonActionEvent(com.codename1.ui.events.ActionEvent ev) {
        this.gui_Button.setText("I clicked on it");
}
```

**Comment by seinecle** [comment]
Le dernier échange de cette conversation date d'une semaine. Je clos cette "issue". Vous pourrez la réouvrir à tout moment si vous avez besoin d'assistance supplémentaire sur cette question précise. Si vous avez une question portant sur un sujet différent, ouvrez une nouvelle issue.
