### ISSUE TITLE
Suite au problème "gui_Label" 

### ISSUE THREAD

**Issue by LouisBrach** [seinecle/codapps#38]
Bonjour Monsieur,

Même après avoir recréer une application, j'ai toujours le même problème (je ne peux plus avancer avant la deadline de vendredi pouvez-vous m'aider à résoudre ce problème cryptique ?). J'ai pourtant suivi vos conseils et décocher ce qu'il fallait mais le preview refuse de s'afficher.... gui_Label n'est pas reconnu

![image](https://user-images.githubusercontent.com/35778830/36432647-014a5c2a-165b-11e8-873a-33fd8f0ca638.png)

**Comment by LouisBrach** [comment]
Même en téléchargeant NetBean sur un autre ordinateur, j'ai le même problème...

**Comment by seinecle** [comment]
Bonjour,
Je vous ai répondu dans l'issue #19 et donc je clos celle-ci.
