### ISSUE TITLE
Build Fails quand je crée des containers 

### ISSUE THREAD

**Issue by MathildeSe** [seinecle/codapps#39]
Bonjour, 

Après avoir passé beaucoup de temps dessus et pensant avoir fait exactement ce qu'il fallait je n'arrive pas à aboutir à la preview. Il semble y avoir beaucoup d'erreurs qui l'empêche de se lancer. J'ai beau chercher, je ne vois pas où sont les problèmes... Je vous joins des screens des erreurs indiquées. En vous remerciant par avance.

Mathilde Serrot

![2018-02-20 1](https://user-images.githubusercontent.com/35896504/36438121-38374e24-1669-11e8-94f2-d60387345e96.png)
![2018-02-20 2](https://user-images.githubusercontent.com/35896504/36438122-385d5eb6-1669-11e8-8243-86c830ed99f7.png)
![2018-02-20 3](https://user-images.githubusercontent.com/35896504/36438123-387b7400-1669-11e8-8f0f-fa3b2e6fb133.png)
![2018-02-20 4](https://user-images.githubusercontent.com/35896504/36438124-389dd068-1669-11e8-97c2-795b12d9434d.png)
![2018-02-20 5](https://user-images.githubusercontent.com/35896504/36438125-38bb8f36-1669-11e8-9314-40fda1408aaa.png)
![2018-02-20](https://user-images.githubusercontent.com/35896504/36438126-390ebf4e-1669-11e8-880b-28e55d616486.png)

**Comment by seinecle** [comment]
Bonjour,
Il y a des espaces dans le nom de vos Components (Container 1, Container 2 ...).
Les noms de variable ne doivent pas comporter d'espace donc choisissez Container1 Container2 etc.

Malheureusement cette erreur ne peut être corrigée simplement et vous devez recommencer une nouvelle app.

Je le mentionne à qq endroits dans la leçon  mais pas systématiquement.  Mes excuses, vous avez dû vous arracher qq cheveux.

Ps: vous serez sans doute encore bloquée par la suite, mais sur des choses plus simples à résoudre.

**Comment by MathildeSe** [comment]
Bonjour,

Merci de votre réponse, je re tenterai l'expérience ce soir en espérant que ça fonctionne. Je reviendrai sûrement vers vous d'ici vendredi si ça ne marche toujours pas.


Mathilde Serrot 


   Clement Levallois --- Re: [seinecle/codapps] La preview ne s'afiche pas (#39) --- 
    De :"Clement Levallois" <notifications@github.com>A :"seinecle/codapps" <codapps@noreply.github.com>Cc :"MathildeSe" <mathilde.serrot@edu.emlyon.com>, "Author" <author@noreply.github.com>Date :mer., 21 févr. 2018 08:55Objet :Re: [seinecle/codapps] La preview ne s'afiche pas (#39)
  
  Bonjour, Il y a des espaces dans le nom de vos Components (Container 1, Container 2 ...). Les noms de variable ne doivent pas comporter d'espace donc choisissez Container1 Container2 etc. 
 Malheureusement cette erreur ne peut être corrigée simplement et vous devez recommencer une nouvelle app. 
 Je le mentionne à qq endroits dans la leçon mais pas systématiquement. Mes excuses, vous avez dû vous arracher qq cheveux. 
 Ps: vous serez sans doute encore bloquée par la suite, mais sur des choses plus simples à résoudre.

**Comment by MathildeSe** [comment]
Bonjour, 

Je me permets de vous solliciter une nouvelle fois. Cette fois-ci, l’application fonctionne, cependant les différentes images que j’ai mise en place apparaissent en désordre quand je lance la preview alors que tout est en ordre sur gui builder. Y a t’il une solution pour que la mise en page de guibuilder soit la même que sur l’écran de preview ? 
Merci d’avance pour votre réponse.

Mathilde Serrot

Envoyé depuis mon iPad en utilisant IBM Verse

Le 21 févr. 2018 à 08:55:13, notifications@github.com a écrit :

**Comment by seinecle** [comment]
Bonjour,
Il faut ouvrir une issue différente pour chaque question. En l'occurrence, il faut passer en tutoriels le lundi, car les questions de layout sont difficiles à résoudre à distance.
