### ISSUE TITLE
CodenameOne Plugin pas activé

### ISSUE THREAD

**Issue by nbottier** [seinecle/codapps#4]
Bonjour,

J'ai téléchargé CodenameonePlugin comme indiqué en démonstration mais impossible de l'activé, il y a deux flèches comme si Netbeans indiquait que mon installation était invalidée.

Pouvez-vous m'aider ?

Merci d'avance,

Nino Bottier

**Comment by seinecle** [comment]
Pouvez-vous poster une copie d'écran qui montre le problème svp?

**Comment by kaisbelala** [comment]
![capture d ecran 2018-01-28 a 15 06 18](https://user-images.githubusercontent.com/35892832/35483001-024f757c-043d-11e8-882e-bba847b90d72.png)
Bonjour, 

Je rencontre le même problème mais visiblement pas pour les mêmes raisons. Le plugin se télécharge pendant un certain temps puis un message d'erreur apparaît : voir en bas de la capture d'écran.

Kaïs Belala.

**Comment by seinecle** [comment]
C''est un problème proche mais cependant différent. J'ai ouvert une question séparée ici:

https://github.com/seinecle/codapps/issues/5

Et je vais effacer votre post ici dans quelques minutes. Allez sur l'issue que je viens d'ouvrir et cliquez sur "subscribe" pour être notifié des commentaires que je mettrai, pour que nous trouvions une solution.

**Comment by seinecle** [comment]
Je vais clore cette issue. N'hésitez pas à la réouvrir si vous avez des éléments nouveaux à apporter.
