### ISSUE TITLE
NetBeansrefuse de s'installer.

### ISSUE THREAD

**Issue by Robz78** [seinecle/codapps#40]
J'ai essayé de l'installer avec la version 64 bits (mon PC est 64 bits), mais j'ai lemessage d'erreur:

Cannot locate java installation in specified jdkhome.

J'ai donc essayé d'installer Java, mais cela m'est aussi impossible quel que soit le navigateur utilisé. J'ai toujours des messages d'erreur.

**Comment by seinecle** [comment]
Bonjour,
Pouvez vous poster ces messages d'erreur (copie d'écran) svp?

**Comment by Robz78** [comment]
![image](https://user-images.githubusercontent.com/35916419/36492979-be83f75a-172e-11e8-9ccc-27274e20994c.png)

**Comment by Robz78** [comment]
En cliquant sur oui:

![image](https://user-images.githubusercontent.com/35916419/36493007-d282fcb0-172e-11e8-93fc-45bd6d7c485f.png)

**Comment by seinecle** [comment]
Ok et avez vous essayé d'installer Java séparemment? Sinon c'est ici: 

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by Robz78** [comment]
J'ai essayé en utilisant firefox et internet explorer (apparemment chrome n'accepte plus Java) et j'ai aussi eu des messages d'erreur. Voulez-vous que je les poste?

**Comment by seinecle** [comment]
Oui merci (il n'y a aucun rapport avec les navigateurs - Chrome n'accepte pas d'utiliser Java comme plugin dans Chrome, mais ne vous interdit aucunement de télécharger Java, ce n'est qu'un fichier).

**Comment by Robz78** [comment]
![image](https://user-images.githubusercontent.com/35916419/36494957-f4de2d98-1733-11e8-801b-b77a4661bc01.png)

**Comment by seinecle** [comment]
Vous téléchargez bien le fichier sur votre ordi avant de double cliquer dessus pour l'installer, et c'est à ce moment que l'erreur ce produit?

**Comment by Robz78** [comment]
L'installation commence, et le message d'erreur interrompt l'installation.

**Comment by seinecle** [comment]
Bonjour,
Je ne peux pas régler ce problème à distance. Je vous suggère de demander de l'aide à un(e) camarade qui aurait installé NetBeans plus tôt.

**Comment by Robz78** [comment]
Merci pour votre aide.

Je suis malheureusement dans l'incapacité de m'adresser de visu à un camarade d'ici demain soir.
A qui dois-je m'adresser pour éviter d'avoir 0 au travail de demain? J'ai rencontré le même problème pour l'installation de Java sur un autre ordinateur. Malgré mes efforts, je n'ai aucune prise sur la situation.

Je suis conscient que j'aurais sans doute m'y prendre plus tôt, mais je ne pensais pas rencontrer un tel problème.

**Comment by seinecle** [comment]
Il n'y a pas de solution à si brève échéance, sans face à face. Envoyez-moi un email.

**Comment by Robz78** [comment]
C'est fait.
