### ISSUE TITLE
Images dans la preview

### ISSUE THREAD

**Issue by LouisBrach** [seinecle/codapps#41]
Bonjour Monsieur, 

Les images que j'ai insérées dans Gui Builder n'apparaissent pas lors de la preview. Faut-il rentrer une ligne de code dans Codename ? De plus, des éléments que j'ai pourtant supprimé dans Gui Builder apparaissent dans la preview malgré la sauvegarde sur Gui Builder 

Bien à vous, 
Louis Brach

![image](https://user-images.githubusercontent.com/35778830/36485779-3a721818-171d-11e8-9a37-861b7fd957de.png)
![image](https://user-images.githubusercontent.com/35778830/36486266-6a100c14-171e-11e8-8c91-97ce477f6ec7.png)

**Comment by seinecle** [comment]
Bonjour,
Il faudrait utiliser un Border Layout pour être sûr que tout est bien inclus sur l'écran.

**Comment by LouisBrach** [comment]
Le problème subsiste, mes 2 images disparaissent et les Labels ne sont pas correctement alignés

**Comment by seinecle** [comment]
Les layouts sont compliqués à démêler à distance, je sèche... vous pouvez passer en tutoriel les lundis. Un layout moche ne vous pénalise pas pour l'Assignment 1.

**Comment by seinecle** [comment]
Le dernier échange de cette conversation date d'une semaine. Je clos cette "issue". Vous pourrez la réouvrir à tout moment si vous avez besoin d'assistance supplémentaire sur cette question précise. Si vous avez une question portant sur un sujet différent, ouvrez une nouvelle issue.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
