### ISSUE TITLE
Affichage des Images... 

### ISSUE THREAD

**Issue by leadebrincat** [seinecle/codapps#42]
Bonjour, 
J'ai terminé le module trois depuis peu et j'ai alors voulu me servir des containers/layouts pour améliorer la présentation de mon application. 
J'ai suivi les démarches expliquées sur les modules mais je me retrouve soit avec des images ridiculement petites, qui ne permettent même pas de distinguer ce qui est représenté; soit avec morceaux de l'image choisie sur une bande très fine... Je joins une capture pour illustrer mon problème... 
<img width="191" alt="questions" src="https://user-images.githubusercontent.com/36039316/36489138-901bcee6-1725-11e8-9f92-327769cf584a.PNG">

Que dois-je faire ? 

Merci par avance...

**Comment by seinecle** [comment]
Bonjour, avez vous essayé de choisir un Border Layout?

**Comment by leadebrincat** [comment]
Oui c'est un Border Layout avec un Container en Grid Layout pour avoir deux lignes et une colonne...

**Comment by seinecle** [comment]
Ok, ce container doit bien être mis en position "center" dans le Border Layout, c'est le cas?

**Comment by leadebrincat** [comment]
Oui... J'ai bien positionné sur Center... Le deuxième affichage que j'avais ressemblait à cela : 
<img width="189" alt="questions" src="https://user-images.githubusercontent.com/36039316/36494335-0c257094-1732-11e8-99dd-821c8f06aacd.PNG">

Dans tous les cas, on ne voit pas les photos...

**Comment by seinecle** [comment]
Cela demanderait une séance en tutorat en face à face, ce lundi par exemple. Cela ne vous pénalise pas pour l'assignment.

**Comment by leadebrincat** [comment]
Je suis déjà inscrite pour lundi soir ! Merci beaucoup pour vos réponses.
