### ISSUE TITLE
Problème ajouter action au bouton

### ISSUE THREAD

**Issue by PaulineRobinet** [seinecle/codapps#43]
Je n'arrive pas à ajouter une action au bouton, toutes les étapes d'avant fonctionnent, j'ai rentré la ligne de code pour ajouter l'action de modification du label lorsqu'on appuie sur le bouton mais lorsque je clique sur preview j'ai un message d'erreur:
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
Compiling 1 source file to C:\Users\pauline\AppData\Roaming\Microsoft\Windows\Recent\ViewofLyon\build\tmp
C:\Users\pauline\AppData\Roaming\Microsoft\Windows\Recent\ViewofLyon\src\com\gmail\pauline\robinet98\myfirstapp\Form1.java:57: error: reached end of file while parsing
    }
1 error
C:\Users\pauline\AppData\Roaming\Microsoft\Windows\Recent\ViewofLyon\build.xml:57: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)

Que dois-je faire et d'où vient le problème? j'ai déjà recommencé au moins 10 fois

**Comment by PaulineRobinet** [comment]
![codapss](https://user-images.githubusercontent.com/35936202/36491878-1bee69fa-172c-11e8-942c-b2946bd9d959.JPG)
voilà ma ligne de code

**Comment by PaulineRobinet** [comment]
![image](https://user-images.githubusercontent.com/35936202/36492062-8304574e-172c-11e8-95ac-6d237be2dd91.png)
Voilà une capture d'écran qui permet de mieux voir. 

En attente de votre réponse, 

Bien à vous, 
Pauline.

**Comment by seinecle** [comment]
Il manque juste une closing curly bracket `}` à la toute fin de votre fichier je crois.

**Comment by PaulineRobinet** [comment]
Merci beaucoup pour votre aide, cela a fonctionné. Néanmoins je me retrouve à nouveau bloquée lorsque je veux lancer le preview.
![image](https://user-images.githubusercontent.com/35936202/36534703-98fc437c-17c7-11e8-9349-1aac29474cf4.png)
Voilà mon message d'erreur.

**Comment by seinecle** [comment]
C'est assez étrange... est-ce que vous avez "build failed" ou pas?

**Comment by PaulineRobinet** [comment]
Non au contraire, j'ai bien "build sucessful (total time: 33 seconds)", une page pour le preview s'est ouverte, rien ne s'est affiché et au bout de 5 secondes la page de preview s'est refermée et j'ai ce message d'erreur... Et je ne pense pas que ça vienne d'un problème de codage mais plutôt du logiciel netbean car j'ai recréé la form de base "Hi world" du début du cours, avec laquelle je n'avais eu aucune difficulté mais qui maintenant ne veut plus s'ouvrir.
Toutes les mises à jour ont été faites.

**Comment by PaulineRobinet** [comment]
![image](https://user-images.githubusercontent.com/35936202/36541340-d6f3c964-17dd-11e8-8102-dc246d3814e6.png)
Voilà également ce qui s'affiche lorsque j'essaie de lancer le preview.

**Comment by PaulineRobinet** [comment]
Petit update de ma situation:
Je viens de perdre plus d'une heure à supprimer le logiciel netbeans pour le retélécharger et tout recommencer à 0, malheureusement sans succès.
J'ai également vérifié Java sur mon ordinateur, j'ai bien la version la plus récente. 
Peut-être est-ce un problème qui vient de mon ordinateur? Celui-ci est assez vieux et j'avais déjà eu de nombreux soucis pour le cours de Excel, d'après le prof certains plugins n'étaient pas compatibles avec mon ordinateur, trop vieux.
Le souci étant que malheureusement je n'ai que cet ordinateur à disposition pour le moment.
Que puis-je faire (si ce n'est toutes ces mises à jour que j'ai essayées) d'ici l'assignement de demain ?

Merci par avance de votre réponse, 
Bien à vous, 
Pauline.

**Comment by seinecle** [comment]
Bonjour,
Maintenant que je vois le message d'erreur je comprends mieux. Ce n'est pas en relation avec NetBeans. Le message indique une erreur à la ligne 52 de votre fichier Form1. Pouvez vous m'envoyer un screenshot de cette ligne svp?

**Comment by PaulineRobinet** [comment]
![image](https://user-images.githubusercontent.com/35936202/36552552-6b43bdf6-17fa-11e8-91bb-e5a477b7f7b8.png)
Voici mes lignes de code. Il me semble que j'avais ajouté 2 fois la même photo mais de 2 façons différentes, la 1ère fois juste en tant qu'image dans la form, la 2è fois en tant que fond d'écran.

**Comment by seinecle** [comment]
Qq choses à tenter:
- supprimer la photo dans le GuiBuilder et aussi dans theme.res
- sauvegarder theme.res
- sur votre ordi, renommer votre photo en enlevant l'espace (les espaces dans les noms sont potentiellement sources de problème)
- puis la reimporter dans theme.res, sauvegarder
- faire un click droit sur le nom de votre projet et choisir "clean and build"
- si vous avez un build failed, postez la copie d'écran ici
- sinon ouvrir le GuiBuilder de votre Form et mettre la photo dans le Form, ca devrait marcher normalement...

**Comment by PaulineRobinet** [comment]
J'ai finalement fait le travail et recommencé à 0 depuis un autre ordinateur où tout à fonctionné correctement.

Merci pour votre aide et vos reponses.
