### ISSUE TITLE
Problème button/label 

### ISSUE THREAD

**Issue by LouiseRzasa** [seinecle/codapps#44]
Bonjour, au moment d'insérer la ligne "this.gui_Label.setText("pressed!");", Netbeans me dit qu'il y a une erreur, mais je n'arrive pas à voir d'où elle provient. 
Merci, 
![capture d ecran 2018-02-21 a 17 58 48](https://user-images.githubusercontent.com/36564530/36493966-1e2fc88a-1731-11e8-9487-a52a4b2ed198.png)

**Comment by seinecle** [comment]
Bonjour,
L'accolade fermante en ligne 53 doit être déplacée en ligne 56. Est-ce que cela marche mieux?

**Comment by LouiseRzasa** [comment]
Non, cela ne fonction toujours pas. 
![capture d ecran 2018-02-21 a 18 08 58](https://user-images.githubusercontent.com/36564530/36494453-541b03e6-1732-11e8-8e6a-57ea99e6b913.png)

**Comment by seinecle** [comment]
Vous avez supprimé l'accolade fermante de la ligne 54: remettez-la. Il doit y a voir deux accolades fermantes.

**Comment by LouiseRzasa** [comment]
Comme ceci? 
![capture d ecran 2018-02-21 a 18 15 48](https://user-images.githubusercontent.com/36564530/36494733-444934b4-1733-11e8-93a4-4d50a9f3b1a1.png)

**Comment by seinecle** [comment]
Non, les deux accolades fermantes doivent être à la toute fin de votre fichier. Mettez celle de la ligne 54 en ligne 57: ca vous fera celle de la ligne 56, et donc celle de la ligne 57

**Comment by LouiseRzasa** [comment]
![capture d ecran 2018-02-22 a 11 41 49](https://user-images.githubusercontent.com/36564530/36533961-72f8fcc6-17c5-11e8-8cc7-69ad32b88a2c.png)

J'ai tout recommencé et j'ai exactement écrit ce qu'il faut obtenir mais ça ne marche toujours pas.

**Comment by seinecle** [comment]
Pardon mais je ne sais pas comment le dire: il faut 2 accolades fermante à la fin:

- vous avez en ligne 43: `}`
- alors qu'il vous faut: `}}`

J'espère que c'est plus clair.

**Comment by LouiseRzasa** [comment]
Merci. J'ai rencontré un autre problème également, quand je mets des photos dans GuiBilder avec Spanlabel, elles n'apparaissent pas sur Netbeans (malgré le faut que j'enregistre bien à chaque fois GuiBilder). Il n'y a en fait que le fond d'écran qui apparaît. 
![capture d ecran 2018-02-22 a 12 58 25](https://user-images.githubusercontent.com/36564530/36537439-6dca5eb0-17d0-11e8-9b1f-3d6e657a6baf.png)
![capture d ecran 2018-02-22 a 12 58 52](https://user-images.githubusercontent.com/36564530/36537446-740bbe40-17d0-11e8-9e91-190503b0292a.png)

**Comment by seinecle** [comment]
Bonjour,
Puis-je vous demander de poster cette seconde question dans une nouvelle issue que vous créerez pour l'occasion? C'est une façon plus organisée de retrouver les questions et leur solution.
