### ISSUE TITLE
Problem for screen 2

### ISSUE THREAD

**Issue by jeangaboriau** [seinecle/codapps#45]
Bonjour, je n'arrive pas à ajouter le screen 2. Cela m'affiche une erreur: String Index out of range:   -4 
![capture d ecran 2018-02-22 a 11 38 58](https://user-images.githubusercontent.com/35913949/36533973-7b20b736-17c5-11e8-8053-06f547a8e486.png)

**Comment by seinecle** [comment]
Vous avez fait un clic droit au mauvais endroit pour créer ce fichier. Ciblez bien le répertoire qui porte le nom de votre package name pour faire le clic droit (revoyez le schéma de la leçon [ici](https://seinecle.github.io/codapps/generated-html/creating-a-form-two-methods.html#_2_another_possibility_creating_a_form_without_coding_with_the_gui))

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
