### ISSUE TITLE
Problème mise en page

### ISSUE THREAD

**Issue by MathildeSe** [seinecle/codapps#46]
Bonjour,

Cette fois-ci l’application fonctionne, il y a juste un problème de mise en page lorsque je lance la preview. Tout est en désordre et ne correspond pas à la mise en page sur gui builder. Est ce que je dois supprimer des images où il existe un moyen de tout agencer correctement ?

Merci d’avance pour votre réponse. 

Mathilde Serrot

**Comment by seinecle** [comment]
Il faut passer en tutoriels le lundi pour résoudre ce genre de problèmes de layout.
