### ISSUE TITLE
Trouver Codename One plugin

### ISSUE THREAD

**Issue by fleurBr** [seinecle/codapps#47]
"Codename One" ne s'affiche pas dans les "available plugins" ? Je ne sais pas ou le trouver pour l'installer

**Comment by seinecle** [comment]
Peut-être est-il déjà installé? Verifiez dans l'onglet "Installed".

**Comment by seinecle** [comment]
Bonjour, 

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
