### ISSUE TITLE
Problème photo Gutbilder/Netbeans

### ISSUE THREAD

**Issue by LouiseRzasa** [seinecle/codapps#48]
Merci. J'ai rencontré un autre problème également, quand je mets des photos dans GuiBilder avec Spanlabel, elles n'apparaissent pas sur Netbeans (malgré le faut que j'enregistre bien à chaque fois GuiBilder). Il n'y a en fait que le fond d'écran qui apparaît.

![capture d ecran 2018-02-22 a 12 58 25](https://user-images.githubusercontent.com/36564530/36537766-64ea8a3a-17d1-11e8-9781-836fdc09900f.png)
![capture d ecran 2018-02-22 a 12 58 52](https://user-images.githubusercontent.com/36564530/36537801-82025c2e-17d1-11e8-913a-baef950fb12c.png)

**Comment by seinecle** [comment]
Puis-je voir une copie d'écran du GuiBuilder de votre Form1 svp?

**Comment by seinecle** [comment]
Bonjour, la dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
