### ISSUE TITLE
probleme avec Gui Builder 

### ISSUE THREAD

**Issue by fleurBr** [seinecle/codapps#49]
Bonjour, 

Le cours indique que pour ouvrir le premier écran de notre appli, il faut faire clique droit sur "screen"en dessous de "my application" et sélectionner Gui Builder
mais je n'ai pas la section "Screen"...Ai je raté une étape ?

![capture d ecran 2018-02-22 a 14 16 49](https://user-images.githubusercontent.com/36731674/36540434-ab0908e4-17da-11e8-937f-1f1f20cb8162.png)

**Comment by fleurBr** [comment]
j'ai ce message là
![capture d ecran 2018-02-22 a 14 48 30](https://user-images.githubusercontent.com/36731674/36541570-a77f0c9c-17de-11e8-82ed-ea6d42be6229.png)

**Comment by seinecle** [comment]
Il faut faire un clic droit sur `io.codapps.BouronFleurApp` et choisir la création d'un Form dans le menu. Tout est expliqué [ici](https://seinecle.github.io/codapps/generated-html/creating-a-form-two-methods.html#_2_another_possibility_creating_a_form_without_coding_with_the_gui).
