### ISSUE TITLE
Unable to connect to the update center

### ISSUE THREAD

**Issue by seinecle** [seinecle/codapps#5]
Issue reported by @kaisbelala

![35483001-024f757c-043d-11e8-882e-bba847b90d72](https://user-images.githubusercontent.com/1244100/35483126-b4912acc-043e-11e8-8457-fcf1c1d6500e.png)

**Comment by seinecle** [comment]
bonjour,

cela semble venir d'une mauvaise connexion internet. Pouvez vous re essayer d'un endroit différent (sur un autre wifi) et poster ici ce que ca donne?

**Comment by kaisbelala** [comment]
C'était effectivement un simple problème de connexion.

Merci !
