### ISSUE TITLE
Fail to submit screenshot

### ISSUE THREAD

**Issue by NyakondaZ** [seinecle/codapps#50]
I have been try to submit my screenshot check the problem error on the attached picture 
![screenshot_20180222-150527](https://user-images.githubusercontent.com/17197134/36540678-fa98e4ac-17e3-11e8-8590-34d8d49b990b.jpg)

**Comment by seinecle** [comment]
Bonjour, réeesayez dans quelques puis envoyez-moi un email si le problème persiste.

**Comment by NyakondaZ** [comment]
Hello , its still repeating the same problem. Help me on that. Wanna
progress with my course

Attached is my Screenshot of the application I tried to create with netbeans

**Comment by seinecle** [comment]
Please send me an email.

**Comment by NyakondaZ** [comment]
What is your email?

**Comment by seinecle** [comment]
Can you please find it in the syllabus of the course.

**Comment by seinecle** [comment]
Can you please find it in the syllabus of the course.

**Comment by seinecle** [comment]
Bonjour, la dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
