### ISSUE TITLE
Problème ouverture preview sur Netbeans

### ISSUE THREAD

**Issue by LouiseRzasa** [seinecle/codapps#51]
Bonjour, j'ai fini mon écran sur Guibuilder (nommé Form1) mais je n'arrive pas à l'ouvrir sur Netbeans, malgré le fait que j'ai tout recommencé à 0 sur Netbeans. J'ai insérer ces phrases pour introduire la forme mais l'écran preview ne s'ouvre pas. 

Form1 myForm1 = new Form1();
    myForm1.getToolbar().setUIID("Container");
    myForm1.getToolbar().hideToolbar();
    myForm1.show();

Je vous joins mon écran netbeans ainsi que les justifications d'erreur dans je lance la preview. 
![capture d ecran 2018-02-22 a 14 37 32](https://user-images.githubusercontent.com/36564530/36541389-0633b644-17de-11e8-88e3-05d1392f25c5.png)
![capture d ecran 2018-02-22 a 14 37 46](https://user-images.githubusercontent.com/36564530/36541393-0934725c-17de-11e8-9d69-ed08eb6fa141.png)

**Comment by seinecle** [comment]
Bonjour,

Votre Form s'appelle Form2 pas Form1, donc mettez `Form2` dans les lignes de code au lieu de Form1.

**Comment by LouiseRzasa** [comment]
J'ai recommencé car j'ai toujours peur de faussé quelque chose mais le problème se représente (cette fois ci j'ai justement bien remis form1). Le problème est donc que toutes les infos présente sur Guibilder ne se présente pas sur la preview Netbeans. 
![capture d ecran 2018-02-22 a 17 30 28](https://user-images.githubusercontent.com/36564530/36550770-5b0f7b36-17f6-11e8-8ed0-4f3af58ed844.png)
![capture d ecran 2018-02-22 a 17 30 37](https://user-images.githubusercontent.com/36564530/36550779-60679276-17f6-11e8-8f20-25a69b0d9a7c.png)

**Comment by seinecle** [comment]
C'est une question de layout, à résoudre en tutoriels en face à face. Cela ne pénalisera pas votre note pour l'Assignment 1.

**Comment by LouiseRzasa** [comment]
Je peux poster une photo ou toutes les photos n'apparaissent donc pas pour l'assagissement 1? (comme celle ci par exemple)

**Comment by seinecle** [comment]
oui
