### ISSUE TITLE
plantage au moment de "Setting an image as the background of the Form"

### ISSUE THREAD

**Issue by AudeJ** [seinecle/codapps#52]
Bonjour, 

Alors que je m’apprêtais à définir le background de mon form sur Gui Builder après avoir uploadé une image sur theme.res selon le process décrit quelques slides plus tôt, le truc a planté.
Plus précisément, lorsque j'appuyais sur les trois petits points à droite de Bg image comme décrit en étape 2 de la figure 12, rien ne se passait.
Après avoir réitéré l'opération, et constaté à plusieurs reprises que rien ne bougeait, j'ai choisi d'enregistrer le tout et de fermer Gui Builder pour le rouvrir en croisant les doigts pour que le bug ait disparu. 
Quelle ne fut pas ma surprise en cliquant sur Form1.java>Gui Builder d'obtenir le message d'erreur suivant :  "The project theme.res file either could not be found, or it contains no themes. Please ensure that the project includes a valid theme.res file etc. try to open the Gui Builder again" sur fond gris avec "exit" pour seule issue. 

![capture d ecran 2018-02-22 14 51 57](https://user-images.githubusercontent.com/36734928/36542909-77e307e6-17e2-11e8-9e05-6ec86552f05d.png)

Quelqu'un sait-il m'indiquer comment sortir de cette impasse ?
Merci d'avance, 
Cordialement, 
Aude JOULOT

**Comment by AudeJ** [comment]
J'ai finalement réussi à contourner ce problème en ajoutant un thème (le thème par défaut) dans theme.res. Malheureusement cela a pour conséquence d'afficher une bande blanche en haut de mon Form lorsque je lance l'aperçu de mon application.

Par ailleurs, je ne sais pas si cela devrait m'alarmer mais le fait de lancer un aperçu de mon app affiche sur Netbeans des messages d'erreurs en rouge (coin inférieur droit "output" de NetBeans), du type : 
" févr. 22, 2018 3:23:41 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5." 
ou encore : 
"Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller code size and wider device support" 

Merci de m'indiquer, si cela est possible, comment 
![capture d ecran 2018-02-22 15 34 50](https://user-images.githubusercontent.com/36734928/36544124-f5e1fa82-17e5-11e8-9246-3d0e74b6f977.png)
résoudre ces petits pépins. 
Cordialement,
Aude JOULOT

**Comment by AudeJ** [comment]
J'ai finalement réussi à contourner ce problème en ajoutant un thème (le thème par défaut) dans theme.res. 

Reste un tout petit problème : je ne sais pas si cela devrait m'alarmer mais le fait de lancer un aperçu de mon app affiche sur Netbeans des messages d'erreurs en rouge (coin inférieur droit "output" de NetBeans), du type :
" févr. 22, 2018 3:23:41 PM java.util.prefs.WindowsPreferences
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5."
ou encore :
"Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller code size and wider device support"

![capture d ecran 2018-02-22 15 34 50](https://user-images.githubusercontent.com/36734928/36544278-5eb7a43a-17e6-11e8-8938-0a6abf8c7ccf.png)

**Comment by seinecle** [comment]
Bonjour,

Ouf, cette histoire de theme.res était compliquée.

Sur le rouge: pas de souci, ce ne sont que des infos / warnings, pas des erreurs.

**Comment by AudeJ** [comment]
C'est noté, merci !
