### ISSUE TITLE
le fichier est trop lourd pour utiliser la version gratuite 

### ISSUE THREAD

**Issue by paulinecasabianca** [seinecle/codapps#53]
Bonjour, 

je suis a la dernière étape, mais le fichier est trop lourd pour la version gratuite, voila le message qui s'affiche 

![capture d ecran 2018-02-22 a 16 13 23](https://user-images.githubusercontent.com/35935902/36546290-53e465a2-17eb-11e8-805b-bae41561b17d.png)

**Comment by seinecle** [comment]
Bonjour,

Il faut supprimer certaines de vos images trop volumineuses:

- commencez par supprimer ces images dans les Form où elles apparaissent.
- allez sur theme.res et supprimez les images: 

![](https://docs.google.com/drawings/d/e/2PACX-1vTmKr7r_66aV9QiIfAZV_bSo1P-MnqCGSgcNgWOfNYCxSc7Gmk45RF87Mr8Ej8G3QsoiryTXFy5jh8-/pub?w=1438&h=964)

- si vous voullez réinserer plus d'images, faites bien attention qu'elles soient de petite taille (100kb par exemple). C'est largement suffisant pour qu'elles s'affichent bien à l'écran.

Je vous confirme que les apps de trop grande taille sont toujours dues à des images trop volumineuses. Le nombre de de Form ou de Button dans votre app.. a une influence marginale sur la taille de l'app.

**Comment by seinecle** [comment]
Bonjour, la dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
