### ISSUE TITLE
Problèm avec AutoLayout

### ISSUE THREAD

**Issue by fleurBr** [seinecle/codapps#54]
bonjour, 

Gui Builder semble bloquer et je ne peux pas modifier les layout et organiser mon appli
voici le message que je reçois : 
![capture d ecran 2018-02-22 a 16 41 30](https://user-images.githubusercontent.com/36731674/36547678-b612144c-17ee-11e8-9af8-3b3d57a8b0af.png)

Merci pour votre aide

**Comment by seinecle** [comment]
Bonjour,
Vous avez créé votre Form en laissant le mode autolayout coché. Vous devez créer un nouveau Form en prenant garde à bien décocher cette option. Voir cette question #36 qui évoque le même problème.
