### ISSUE TITLE
Impossible d'ouvrir le GUI Builder

### ISSUE THREAD

**Issue by clementinerey** [seinecle/codapps#55]
![capture d ecran 2018-02-22 a 19 13 47](https://user-images.githubusercontent.com/36741849/36556201-a852e7e4-1804-11e8-8220-1cf4a397fc1e.png)
Bonjour, 

J'ai quasiment fini la "form" de mon application mais Gui Builder a arrêté de fonctionner à un moment donné, je l'ai donc relancé mais lorsque je clique droit sur "Form2" puis sur Gui Builder, rien ne s'affiche. De plus lorsque je clique sur la flèche verte sur NetBeans pour "preview" mon application, java s'ouvre puis se referme automatiquement avant que la preview ne s'affiche (tandis que cela fonctionnait au début, lorsqu'il fallait afficher "Hi world").

Je vous remercie par avance de votre aide

![capture d ecran 2018-02-22 a 18 57 00](https://user-images.githubusercontent.com/36741849/36555880-9d506cf0-1803-11e8-9a54-d07da6ebc548.png)

**Comment by seinecle** [comment]
Bonjour,
Difficile à diagnostiquer. Que ce passe-t-il si vous créez un nouveau Form (Form3) et que vous adaptez les lignes de code pour qu'il se lance au démarrage? Si le problème persiste, recommencez une nouvelle app (fastidieux mais relativement rapide).

**Comment by clementinerey** [comment]
Bonjour, 
Merci de votre réponse. Il m'était impossible de faire "preview", dc j'avais déjà recommencé avec "Form2" qui se lançait bien au démarrage, mais c'est par la suite que cela ne fonctionnait plus. Je vais essayer de recommencer une nouvelle app, peut-être avec moins d'informations dessus (elle était peut-être trop lourde?).
Merci

**Comment by seinecle** [comment]
Non la taille ne devrait pas être un souci, mais effectivement c'est une bonne idée de recommencer depuis un projet vide.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
