### ISSUE TITLE
Mauvais Form qui s'affiche dans la preview / mon Form ne s'affiche pas dans la preview

### ISSUE THREAD

**Issue by leadebrincat** [seinecle/codapps#56]
Bonjour, 
Etant donné que les consignes de l'Assignment de demain sont assez précises et ne correspondent pas à ce que j'ai fait dans mon application, j'ai voulu recommencer "un Form" spécialement pour l'Assignement... Mon problème est qu'à chaque fois que je clique sur la flèche verte de previem c'est Form1 qui s'affiche et non pas Form2... Comment faire afficher Form2 ? 
Merci d'avance !

**Comment by seinecle** [comment]
Il faut modifier les 2 lignes de code mentionnées [dans cette partie du cours](https://seinecle.github.io/codapps/generated-html/creating-a-form-two-methods.html#anchor-2): substituez Form1 par Form2

Cette question est aussi discutée dans une autre issue: #25

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
