### ISSUE TITLE
impossible de donner une fonction au "button"

### ISSUE THREAD

**Issue by etienneroy01** [seinecle/codapps#57]
Bonsoir, 
j'ai essayé plusieurs fois de conférer une fonction à "button", notamment en utilisant le code donné sur votre site. le message d'erreur est le suivant : 

Le type d'élément Label doit être suivi des component suivants <, >, /
Il y a une ampoule à gauche de la ligne où je rentre le code, pourtant j'ai rentré le bon nom de label. 
Pourriez vous m'aider sur ce point ? 
Merci !

**Comment by seinecle** [comment]
Bonsoir,
Il me faudrait une copie d'écran? Merci.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
