### ISSUE TITLE
Problème de code sur la fonction bouton

### ISSUE THREAD

**Issue by chloesarayed** [seinecle/codapps#58]
Bonsoir, 
Lorsque que je fais le preview de l'application tout est décalé par rapport à ce que j'ai fais. De plus, l'application ne se lance pas, Net Beans m'annonce une erreur, je vous met le screen ./Users/ChloeSarayeddine/Desktop/Capture d’écran 2018-02-22 à 20.31.28.png

**Comment by chloesarayed** [comment]
/Users/ChloeSarayeddine/Desktop/Capture d’écran 2018-02-22 à 20.31.28.png

**Comment by chloesarayed** [comment]
![capture d ecran 2018-02-22 a 20 31 28](https://user-images.githubusercontent.com/35938795/36560619-8aaa5bfc-1811-11e8-9630-b9f99deb0b77.png)

**Comment by seinecle** [comment]
Bonjour,
Il y a dû y avoir un copier-coller malheureux car toute une partie du code a disparu de votre Form (Screen1). Créez un nouveau Form pour repartir sur de bonnes bases.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
