### ISSUE TITLE
problème avec espace dans le nom d'une Label ou Button ou Container

### ISSUE THREAD

**Issue by camillemrnt** [seinecle/codapps#59]
Je pense que j'ai fais une fausse manip et je n'arrive plus à la résoudre pour pouvoir avoir la preview de mon application
<img width="978" alt="capture d ecran 2018-02-22 a 22 33 17" src="https://user-images.githubusercontent.com/36190228/36565351-7b9f93c0-1820-11e8-866f-4803fd337063.png">
<img width="978" alt="capture d ecran 2018-02-22 a 22 33 09" src="https://user-images.githubusercontent.com/36190228/36565355-7eefa772-1820-11e8-9816-0cfe0c2a1716.png">
<img width="547" alt="capture d ecran 2018-02-22 a 22 32 58" src="https://user-images.githubusercontent.com/36190228/36565359-817396ca-1820-11e8-80f0-dd8b053a1a27.png">

**Comment by camillemrnt** [comment]
( les spremiers screens sont les messages d'erreurs et le dernier celui du code)

**Comment by seinecle** [comment]
Oui vous faites:

`Form2 my Form2 = new Form1();
`
- il faut enlever l'espace entre `my` et `Form2`
- `Fomr1` doit être `Form2`

donc vous devez avoir: `Form2 myForm2 = new Form2();`

**Comment by camillemrnt** [comment]
j'ai bien modifié mais cela ne fonctionne toujours pas 
<img width="1014" alt="capture d ecran 2018-02-23 a 11 12 33" src="https://user-images.githubusercontent.com/36190228/36589120-8840ddf4-188a-11e8-9a69-5aed2864a88e.png">

**Comment by camillemrnt** [comment]
<img width="1014" alt="capture d ecran 2018-02-23 a 11 12 33" src="https://user-images.githubusercontent.com/36190228/36589124-8f4f2024-188a-11e8-81e9-2abba61064ea.png">

**Comment by camillemrnt** [comment]
<img width="1021" alt="capture d ecran 2018-02-23 a 11 12 39" src="https://user-images.githubusercontent.com/36190228/36589133-9537d10c-188a-11e8-9e0e-5f36cfcf01d1.png">

**Comment by camillemrnt** [comment]
j'ai essayé d'un autre ordinateur et c'est toujours le meme message

**Comment by seinecle** [comment]
votre Label s'appelle `camille martin` et ce nom comporte un espace: cela "casse" votre code. Supprimez votre Label dans le GuiBuilder et créez-en une nouvelle avec un nom qui ne comporte pas d'espace.

**Comment by camillemrnt** [comment]
merci beaucoup mais j'en n'ai recrée un mais toujours le meme message
<img width="1156" alt="capture d ecran 2018-02-23 a 14 48 55" src="https://user-images.githubusercontent.com/36190228/36597274-e8232f6a-18a8-11e8-8947-53bd3e2655e9.png">
<img width="1072" alt="capture d ecran 2018-02-23 a 14 49 02" src="https://user-images.githubusercontent.com/36190228/36597279-eadbd626-18a8-11e8-957a-2b8cd97fe944.png">

**Comment by seinecle** [comment]
Ok c'est ce que je craignais:
- comme discuté ci-dessus, votre Label comporte un espace dans son nom (camille martin), ce qui "casse" le code,
- vous supprimez la Label dans le GUI Builder mais cela ne résout pas le problème: NetBeans n'est pas arrivé à supprimer la Label dans un fichier interne, qui en garde la trace.

Jusqu'ici j'ai recommandé aux étudiants dans ce cas de recommencer une app, mais j'ai trouvé le fichier qui doit être réparé pour que votre app fonctionne de nouveau. Les étapes:

1. sur votre ordi, trouvez le répertoire où les fichiers de votre app se trouvent. Ce répertoire doit avoir pour nom le nom de votre app. La mienne s'appelle MontainViews:

![repair-app-1](https://user-images.githubusercontent.com/1244100/36603283-918192c0-18ba-11e8-90d1-f7c5bd4f1dda.jpg)

2. Ouvrez ce répertoire et allez dans le sous-répertoire suivant:

`MountainViews\res\guibuilder\net\clementlevallois\myfirstapp`

*Ici évidemment le nom des sous-répertoires dépendra du package name que vous avez choisi, l'idée est d'aller dans* `res -> guibuilder -> etc.`

3. Vous devriez voir des fichiers qui correspondent à chacun de vos Forms:

![repair-app-2](https://user-images.githubusercontent.com/1244100/36603488-315188fa-18bb-11e8-9a82-af18af7babda.jpg)

4. Ouvrez le fichier du Form qui vous pose problème avec un éditeur de texte ([voici comment](https://www.benchmarkemail.com/help-FAQ/answer/how-do-i-locate-textedit-or-notepad-on-my-computer))

5. Ca devrait ressembler à ca:

![repair-app-3](https://user-images.githubusercontent.com/1244100/36603860-6b9629d4-18bc-11e8-9539-43f6bd74586d.jpg)

6. Supprimez les lignes qui correspondent au Component que vous aviez supprimé dans le GUI Builder, mais qui est encore présent dans ce fichier (c'est la source du problème!):

![repair-app-4](https://user-images.githubusercontent.com/1244100/36603968-b2bac496-18bc-11e8-960b-379615e69830.jpg)

*Soyez attentive ici à supprimer exactement ce qu'il faut, pas plus.*

7. Sauvegardez le fichier (File -> Save).

8. Revenez dans NetBeans et faite un clic droit sur le nom de votre projet -> `Clean and Build` et *normalement* tout devrait rentrer dans l'ordre.

Ca marche?

**Comment by camillemrnt** [comment]
cela a marché merci !

**Comment by camillemrnt** [comment]
encore une question 
je ne comprends pas pourquoi mon bouton pressed n'est pas au milieu comme l'exmple du module , la il se trouve sur un label
<img width="189" alt="capture d ecran 2018-02-23 a 18 09 47" src="https://user-images.githubusercontent.com/36190228/36606750-efc661d0-18c4-11e8-8aab-6ef0e77b7339.png">
<img width="189" alt="capture d ecran 2018-02-23 a 18 09 47" src="https://user-images.githubusercontent.com/36190228/36606762-f3d9cf46-18c4-11e8-9218-f5f6bea2771e.png">
<img width="197" alt="capture d ecran 2018-02-23 a 18 09 52" src="https://user-images.githubusercontent.com/36190228/36606770-f7d99eaa-18c4-11e8-94d3-c31244963862.png">
<img width="180" alt="capture d ecran 2018-02-23 a 18 09 57" src="https://user-images.githubusercontent.com/36190228/36606774-fa819da6-18c4-11e8-994e-3add4c43ed21.png">
<img width="695" alt="capture d ecran 2018-02-23 a 18 10 15" src="https://user-images.githubusercontent.com/36190228/36606778-fd2686ac-18c4-11e8-9cb3-72430d51c545.png">

**Comment by seinecle** [comment]
Pouvez vous poster cette nouvelle question dans une issue séparée svp?
