### ISSUE TITLE
Couleur et style d'un Span Label

### ISSUE THREAD

**Issue by aron2101** [seinecle/codapps#6]
Bonsoir Monsieur, comment fait-on pour changer la couleur et le style d'un Span Label ?
(pour un Label ca fonctionne en passant par theme.res mais dès que je fais la même opération pour un span label ça ne prend pas)

**Comment by aron2101** [comment]
Merci d'avance et bonne soirée.

**Comment by seinecle** [comment]
Je crois que c'est la partie que vous cherchez:

https://seinecle.github.io/codapps/generated-html/advanced-styling.html#anchor-1

(si cela résout votre problème vous pouvez clore cette "issue")

**Comment by aron2101** [comment]
Merci beaucoup.
