### ISSUE TITLE
problème fonctionnement netbeans à cause de theme.res

### ISSUE THREAD

**Issue by fleurBr** [seinecle/codapps#60]
Bonjour, 

Mon application netbeans est bloquée, même après désinstallation/réinstallation de l'application et redémarrage de l'ordinateur, avez vous une solution pour la faire repartir à zéro?
ci joint une photo du problème 

Merci

Fleur B
![capture d ecran 2018-02-23 a 09 37 43](https://user-images.githubusercontent.com/36731674/36585015-650ea5d6-187c-11e8-9ca9-339356e2f06e.png)
![capture d ecran 2018-02-23 a 09 33 46](https://user-images.githubusercontent.com/36731674/36585016-653269c6-187c-11e8-8707-16f9b7a17337.png)

**Comment by seinecle** [comment]
Dans theme.res vous pouvez cliquer sur "Add a new theme".

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
