### ISSUE TITLE
Problème pour afficher le bouton et label

### ISSUE THREAD

**Issue by maximedpt14** [seinecle/codapps#61]
Bonjour, 
Cela fait une heure que j'essaye de corriger les erreurs sur la commande et le bouton sur mon application ne veut pas s'afficher. Pouvez vous m'indiquer que faire pour qu'il puisse enfin s'afficher svp? 
<img width="1440" alt="capture d ecran 2018-02-23 a 10 34 45" src="https://user-images.githubusercontent.com/35683758/36587494-a0fad37c-1885-11e8-9c77-1bca4bf60641.png">

**Comment by seinecle** [comment]
Bonjour,
Je vous invite à voir ma réponse dans cette question qui posait un problème identique: #44 .

**Comment by maximedpt14** [comment]
J'ai été voir votre réponse mais j'ai appliqué les deux crochets aux deux lignes, mais le problème est par rapport à un point-virgule ? 
<img width="1440" alt="capture d ecran 2018-02-23 a 11 03 47" src="https://user-images.githubusercontent.com/35683758/36588748-571c3fda-1889-11e8-808d-4137dbe7dc79.png">

**Comment by seinecle** [comment]
Oui, effectivement. Il  y a comme un espace qui "casse" le code entre `onUpdateLabel` et `Command`.
Vous pouvez enlever cet espace "à la main" en ligne 45 (j'ai l'impression que vous l'avez fait), mais en fait cette ligne de code est générée automatiquement à partir de qui est dans votre GuiBuilder. Est-ce que vous avez un espace "en trop", dans votre GuiBuilder, dans l'action associée à votre Button?
