### ISSUE TITLE
Ligne de code dans l'action du Button a une erreur

### ISSUE THREAD

**Issue by clementinerey** [seinecle/codapps#62]
Bonjour, 

J'ai fini la Form de mon application mais je n'arrive pas à afficher "Preview", je reçois le message d'erreur ci-joint.

Merci de votre aide
![capture d ecran 2018-02-23 a 10 40 48](https://user-images.githubusercontent.com/36741849/36587872-a3ed76f6-1886-11e8-90e2-a8877c624333.png)

**Comment by seinecle** [comment]
Bonjour,
Il semblerait que vous ayez créé une action associée à un bouton. Vous avez appelé cette action "choix pays". L'espace dans ce nom (entre `choix `et `pays`) casse votre application. Je suis désolé mais il faut recommencer votre app.
Désolé pour l'énervement que cela peut provoquer... c'est un des rares cas où une erreur est si pénalisante.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
