### ISSUE TITLE
Espace dans le nom d'un Component ou d'un Form "casse" l'application

### ISSUE THREAD

**Issue by ThomasBurger69** [seinecle/codapps#63]
Bonjour,
j'ai ajouté un texte et une photo, j'ai suivi les instructions pour que la page 1 de l'appli s'ouvre mais ça ne fonctionne pas... 
Pouvez-vous me dire ce qui ne va pas s'il vous plait? 
Cordialement. 
![capture d ecran 2018-02-23 a 12 22 43](https://user-images.githubusercontent.com/35903800/36592048-711ac234-1894-11e8-83d2-17894d30aa94.png)

**Comment by seinecle** [comment]
Vous avez créé un Form avec le nom `Screen 1`, qui comporte un espace. Cela "casse" votre code. Je pense que vous allez devoir créer une nouvelle appplication car cette erreur est difficile à résoudre. Essayez peut-être de supprimer le fichier `Screen 1.java` (le fichier qui comporte un espace dans le nom), mais pas sûr que cela suffise.

**Comment by ThomasBurger69** [comment]
D’accord je vais essayer .. 
Merci. 

Envoyé depuis mon iPhone en utilisant IBM Verse

Le 23 févr. 2018 à 13:32:26, notifications@github.com a écrit :

**Comment by seinecle** [comment]
Bonjour,

Voici comment faire si vous voulez essayer de régler le problème sans recommencer votre app:
https://github.com/seinecle/codapps/issues/59#issuecomment-368055900

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
