### ISSUE TITLE
Problème dans le code empêche la Preview

### ISSUE THREAD

**Issue by MountAnnapurna** [seinecle/codapps#64]
Bonjour Monsieur, 

J'ai un problème de Preview suite à la mise en place d'un fond d'écran et d'une miniature. 
(Fin du module 2) 
Voici les captures d'écran:

![preview](https://user-images.githubusercontent.com/36763140/36592670-15a8c7c2-1897-11e8-837b-c8d6ee5073cf.PNG)

![screen problem](https://user-images.githubusercontent.com/36763140/36592673-17aae852-1897-11e8-8abd-da074e96db17.PNG)

Auriez-vous une idée du problème ? 
Je vous remercie.

**Comment by seinecle** [comment]
Il semblerait que vous n'ayez pas de Label dans votre Form1?

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
