### ISSUE TITLE
Problème avec Gui_Label

### ISSUE THREAD

**Issue by matth0071** [seinecle/codapps#65]
Dans votre cours, il y a un script qui dit qu'il faut écrire : this.gui_Label.setText("pressed"); or il me souligne gui_Label en rouge en disant qu'il y a une erreur mais je ne comprends pas comment la résoudre.

**Comment by seinecle** [comment]
Pouvez vous poster une copie d'écran svp? Avez-vous bien créé une Label dans votre Form1?

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
