### ISSUE TITLE
le bouton ne fait rien quand on le presse dans la preview

### ISSUE THREAD

**Issue by Dorveaux** [seinecle/codapps#66]
Bonjour Monsieur,
Je suis au module  du cours et je n'arrive pas à associer une fonction au bouton, je ne comprends pas où est l'erreur !
![capture ecran](https://user-images.githubusercontent.com/36296420/36594099-0bac0512-189d-11e8-8b21-c44409d3d7fa.png)
merci de votre réponse, 
bonne journée
Alix Dorveaux

**Comment by seinecle** [comment]
Bonjour,
Ces lignes rouges sont des avertissements mais pas un message d'erreur. Il semble que votre application fonctionne.

**Comment by Dorveaux** [comment]
pourtant, quand je lance la preview voilà ce que ça me donne
![capture ecran 2](https://user-images.githubusercontent.com/36296420/36594688-8847ffde-189f-11e8-9129-b8b5cd1b4c3b.png)

**Comment by Dorveaux** [comment]
et ça ne donne rien quand je clique sur button

**Comment by Dorveaux** [comment]
j'ai essayé de modifier l'erreur en recréant une autre application mais ça a donné le même problème, je ne vois pas comment régler le souci ...

**Comment by seinecle** [comment]
Bonjour,
Ce n'est pas un bug, juste qu'il n'y a rien dans l'action de votre Button. Revoyez la leçon, vous verrez qu'il vous manque une ligne.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
