### ISSUE TITLE
La fenêtre core components n'apparaît pas

### ISSUE THREAD

**Issue by E-macouillard** [seinecle/codapps#67]
Bonjour,

Lorsque j'ouvre le fichier Thème.res, l'interface qui s'ouvre ne ressemble pas à celui de la capture d'écran du tutoriel. Comment faire apparaître l'onglet core components ? Sans cet onglet je ne peux pas suivre les étapes du tutoriel
![screenshotcodapps](https://user-images.githubusercontent.com/36762833/36594616-283190c4-189f-11e8-9b86-91d2733db5bd.png)

**Comment by seinecle** [comment]
Je crois que vous mélangez plusieurs leçon: theme.res est pour changer le style de vos Components (voir leçons du Module 3). Pour créer vos components, vous devez allez dans le GUI Builder (voir leçons du Module 2).

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
