### ISSUE TITLE
Problème pour télécharger Codename One plugin

### ISSUE THREAD

**Issue by suzie64** [seinecle/codapps#68]
A chaque fois que j'essaie de télécharger Codename One et que le téléchargement arrive à 100% j'ai le message suivant qui s'affiche :

Networking problem in
http://plugins.netbeans.org/nbpluginportal/files/nbms/1514532878_com-codename1.nbm

Check your proxy settings or try again later. The server may be unavailable at the moment. You may also want to make sure that your firewall is not blocking network traffic. Your cache may be out of date. Please click Check for Updates to refresh content.

J'ai déjà vidé le cache de chrome. Je ne sais pas quoi faire d'autre. 
Avez vous des conseils pour que ca fonctionne ? 

Merci.

**Comment by seinecle** [comment]
Le serveur peut être encombré en ce moment, c'est rare mais cela arrive. Ré-essayez demain.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
