### ISSUE TITLE
Insertion d'un "Button"

### ISSUE THREAD

**Issue by Thibzbrg** [seinecle/codapps#69]
Bonjour monsieur, je n'arrive malheureusement pas à insérer un simple "Button" lorsque je passe la souri et clique dessus rien ne s'affiche, je ne peux qu'insérer un "span button" ou un "multi button" ...

**Comment by seinecle** [comment]
Bonjour, cela n'est pas très clair. Passez en tutoriel ce lundi.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
