### ISSUE TITLE
 "Codename One" pas disponible quand je crée un nouveau projet

### ISSUE THREAD

**Issue by Ghitaz** [seinecle/codapps#7]
Je suis sur version MAC, et je n'arrive pas à trouver "CodenameOne Project", le premier langage qu'on me propose c'est Java. Ensuite, on m'affiche seulement Name and Location, puis directement "finish", sans le "Package name", "thème" ou "template". 
Merci

**Comment by seinecle** [comment]
Cela indique que le plugin Codename One n'est pas installé (ou mal installé).
Pouvez vous refaire la leçon sur l'installation du plugin et vérifier que tout se passe bien?

**Comment by seinecle** [comment]
Je vais clore cette issue. N'hésitez pas à la réouvrir si vous avez des éléments nouveaux à apporter.
