### ISSUE TITLE
Hi world apparaît à la place de mon écran

### ISSUE THREAD

**Issue by LucasMorenas** [seinecle/codapps#70]
Bonjour Monsieur,

J'ai crée un form avec Gui Builder mais lorsque je retourne sur NetBeans pour afficher la preview, l'image de l'Iphone avec "Hi World" apparait. [
![capture d ecran 2018-02-23 a 16 04 22](https://user-images.githubusercontent.com/36765648/36600887-da764860-18b3-11e8-8669-7ee5eded2c72.png)
](url)

**Comment by seinecle** [comment]
Bonjour, 
Un(e) de vos camarades a eu le même problème, voir la solution ici: #25

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
