### ISSUE TITLE
Problème d'affichage dernière étape Module 2

### ISSUE THREAD

**Issue by Chlodp** [seinecle/codapps#71]
Bonjour Monsieur, 
Je n'ai pas réussi à insérer une image par dessus le fond vert, je l'ai donc insérée directement et lorsque je tente d'afficher l'image de l'application à la fin du Module 2, j'ai ceci et je ne comprends pas pourquoi j'ai 2 fois la ligne alors que je ne devrais pas l'avoir : 
![screen shot 2018-02-23 at 4 33 58 pm](https://user-images.githubusercontent.com/36769063/36602640-cbdf5ee0-18b8-11e8-88f8-7d8ef658f09b.png)

**Comment by seinecle** [comment]
Difficile à régler à distance. Passez lundi pour ce problème.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
