### ISSUE TITLE
proportionnalité avec l'iphone

### ISSUE THREAD

**Issue by matth0071** [seinecle/codapps#72]
Monsieur, la proportionnalité n'est pas du tout respecté entre ma présentation sur Gui Builder et sur Netbeans. 
Voici les captures d'écran, comment puis-je y remédier ? 
Merci d'avance 
![capture d ecran 2018-02-23 a 16 59 57](https://user-images.githubusercontent.com/36743718/36603460-1768b8f0-18bb-11e8-8cd4-a28ce12cfd1e.png)
![capture d ecran 2018-02-23 a 17 00 16](https://user-images.githubusercontent.com/36743718/36603464-19e76676-18bb-11e8-8825-b85af46276a2.png)

**Comment by seinecle** [comment]
Les questions de layout sont difficiles à régler à distance. Passez au tutoriel de lundi pour voir ensemble.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
