### ISSUE TITLE
button ne se sauvegarde pas dans gui_builder

### ISSUE THREAD

**Issue by Lchavanne** [seinecle/codapps#73]
bonjour monsieur,

Apres avoir donné une fonction à mon bouton (UpdateLabelText, etc.), j'ai sauvegardé cela dans gui_builder (des deux manières différentes), puis j'ai écrit la ligne this.gui_Label.setText("pressed!") dans Form1.java, mais quand j'essaie de lancer l'application, elle fail toujours une fois avant de marcher, puis lorsqu'elle s'affiche, soit le bouton n'a pas d'action, soit je ne vois que le Label et le bouton a disparu.
Quand je retourne dans Gui_builder, le bouton a l'air d'avoir disparu, et l'action attachée (UpdateLabelText) n'a pas été sauvegardée. Je ne comprends pas le problème.
voila ce que j'ai quand je retourne dans Gui_builder : 
![capture d ecran 2018-02-23 a 17 43 31](https://user-images.githubusercontent.com/36001145/36606060-d176a098-18c2-11e8-8038-008912f13889.png)

Merci d'avance pour votre réponse.

**Comment by seinecle** [comment]
Votre bouton n'a pas de texte, est ce normal? Vous pouvez passer lundi en tutoriel pour décrire votre problème et le résoudre ensemble.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de deux semaines. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
