### ISSUE TITLE
Le lancement du mode preview ne se fait pas

### ISSUE THREAD

**Issue by PaulineGUEHO** [seinecle/codapps#74]
Bonjour Monsieur Levallois,

Mon application ne se lance pas en preview et je ne comprends malheureusement pas d'où vient le problème ni comment le résoudre, avez-vous une explication ?

Je vous joins un screen,

Merci pour votre aide,
[Netbeans1.pdf](https://github.com/seinecle/codapps/files/1752446/Netbeans1.pdf)
[Netbeans2.pdf](https://github.com/seinecle/codapps/files/1752447/Netbeans2.pdf)

**Comment by PaulineGUEHO** [comment]
Le temps commençant à manquer, je vous joins également un screen de GuiBuilder afin que vous puissiez constater que le travail est fait, il ne se lance simplement pas depuis ma dernière modification sur GuiBuilder alors que tout fonctionnait jusqu'alors.

Je vous prie encore de m'excuser pour la demande au dernier moment, j'ai été surprise par ce problème lié à ma toute dernière modification, 

[GUEHO_Pauline_GuiBuilder.pdf](https://github.com/seinecle/codapps/files/1752929/GUEHO_Pauline_GuiBuilder.pdf)



Pauline Guého

**Comment by seinecle** [comment]
Bonjour,
Pouvez vous reposter vos screenshots en format "photo" (jpg ou png) plutôt que pdf? Ils sont difficiles à lire (ouvrir dans une nouvelle fenêtre, ensuite ils sont perpendiculaires et je dois les tourner, etc.). C'est juste qu'il y a des dizaines de questions sur ce cours (80 exactement à ce jour), cela m'aide beaucoup si elles sont clairement visibles. Merci.

**Comment by PaulineGUEHO** [comment]
![netbeans11](https://user-images.githubusercontent.com/35836611/36641514-fcb793ba-1a30-11e8-8131-0c2f877ccc57.jpg)
![netbeans21](https://user-images.githubusercontent.com/35836611/36641517-03bc33dc-1a31-11e8-88f2-d74a4dfe329e.jpg)

Les voici, merci beaucoup !

**Comment by seinecle** [comment]
Merci. Je ne vois pas la fin de la ligne 84:

- y a-t-il qqch à la fin de la ligne qui soit surligné en rouge?
- quel est le message qui s'affiche quand vous cliquez sur l'icone jaune et rouge dans la marge de la ligne 84?

**Comment by PaulineGUEHO** [comment]
Voici la ligne 84 : 
 public void onUpdateLabelCommand(com.codename1.ui.events.ActionEvent ev, com.codename1.ui.Command cmd) {this.gui_Label_1.setText("pressed!"); 

Rien n'est surligné en rouge, le mot pressed est de couleur orange et l'ensemble de la ligne est souligné en rouge

En cliquant sur l'icône, j'ai le message : create missing javadoc for missing onUpdateLabelCommand

**Comment by seinecle** [comment]
Je crois avoir compris: remplacez `this.gui_Label_1.setText("pressed!")` par `this.gui_Label.setText("pressed!")`

En effet je crois que la `Label` dans votre Form s'appelle Label, pas Label_1

**Comment by PaulineGUEHO** [comment]
Effectivement, un problème résolu !

Reste la ligne 95
Souligné en rouge « private static void setText(String pressed).  {

Je serai au tutorat de 12h en 374,

Encore merci, 

Pauline

**Comment by PaulineGUEHO** [comment]
Et voici la preview finale ! (impossible de la poster sur Brightspace qui n'accepte plus les nouvelles soumissions de fichiers)

![pauline_gueho_preview_app1](https://user-images.githubusercontent.com/35836611/36669884-b7ce8f94-1af6-11e8-96e5-b1c74265c796.jpg)

**Comment by seinecle** [comment]
Bien noté!
