### ISSUE TITLE
Gui Builder ne fonctionne plus 

### ISSUE THREAD

**Issue by MountAnnapurna** [seinecle/codapps#76]
Bonsoir Monsieur,

L'outil Gui Builder ne fonctionne plus. Avant qu'il ne crashe, j'étais en train de modifier les bordures de la photo... Voici le message de notification ainsi que les lignes de code qui signalent le problème:

![error](https://user-images.githubusercontent.com/36763140/36606752-f05bdbca-18c4-11e8-9b55-68b451589fea.PNG)
![probleme code](https://user-images.githubusercontent.com/36763140/36606756-f1f8d9ba-18c4-11e8-9b25-916fa8cc2646.PNG)

Je vous remercie d'avance.

**Comment by seinecle** [comment]
Bonjour,

Y a-t-il un message d'erreur dans votre Form1?

**Comment by MountAnnapurna** [comment]
Non pas de message d'erreur, simplement Gui Builder ne veut pas se lancer. 

![pb](https://user-images.githubusercontent.com/36763140/36615828-e185ff14-18e1-11e8-829f-ce1d79518d49.PNG)

**Comment by seinecle** [comment]
Passez ce lundi svp, c'est assez mystérieux.

**Comment by seinecle** [comment]
Il y a une erreur à la ligne 42 de votre Form, pouvez vous faire une copie d'écran ici?

**Comment by MountAnnapurna** [comment]
La voilà, merci encore à vous ! 

![ligne 42](https://user-images.githubusercontent.com/36763140/36616254-62e4d034-18e3-11e8-8220-8a8d0eac82ef.PNG)

**Comment by seinecle** [comment]
Ça ressemble à un problème avec votre image k2... dans la Label. Il faudrait supprimer la Label, mais sans accéder au Gui builder. Je vous mets dans le commentaire suivant un lien vers une réponse où j'explique comment faire, dans un contexte proche.

**Comment by seinecle** [comment]
https://github.com/seinecle/codapps/issues/59

**Comment by seinecle** [comment]
Bonjour, La dernière réponse à cette issue date de plus de 15 jours. Je la  clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la  réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir  cette issue, mais créez-en plutôt une autre.
--
