### ISSUE TITLE
Erreur passage à la preview

### ISSUE THREAD

**Issue by LisonBel** [seinecle/codapps#77]
Bonsoir, 
J’ai désigné intégralement mon application sur gui builder mais au moment d’afficher la preview, netbeans affiche un message d’erreur et n’ouvre rien du tout... je ne sais plus quoi faire... 
je vous joins un screen du message d’erreur affiché. 
Merci d’avance 
Lison Bel 
![bd6be724-e86f-4c66-8b43-f40b543a2dfd](https://user-images.githubusercontent.com/36737637/36607416-e0e8bd32-18c6-11e8-81cf-46983f9084bf.jpeg)

**Comment by seinecle** [comment]
bonjour,

à la ligne 118 changez `onButtonActionEvent` par `onButton_1ActionEvent`. Cela résout-il votre problème?

Par ailleurs, il est possible de faire des copies d'écran plus simplement qu'en prenant une photo avec votre téléphone, juste en utilisant votre clavier. [Voici comment faire](https://support.apple.com/fr-fr/HT201361).

**Comment by seinecle** [comment]
Bonjour, La dernière réponse à cette issue date de plus de 15 jours. Je la  clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la  réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir  cette issue, mais créez-en plutôt une autre.
--
