### ISSUE TITLE
"The JDK is missing and is required to run some NetBeans modules" au démarage 

### ISSUE THREAD

**Issue by RemyAlbaredes** [seinecle/codapps#78]
Ce message apparaît lorsque je lance le logiciel, bien que je puisse accéder a NetBeans. En revanche il m'est impossible d'ouvrir des "projects" (le menu de gauche est vide) et je pense que c'est dû au fait que je suis obligé de désactiver des plugins pour accéder au logiciel..

**Comment by seinecle** [comment]
En effet. Passez lundi pour régler ça, à distance c'est difficile à diagnostiquer.
