### ISSUE TITLE
Problème installation JDK 8 

### ISSUE THREAD

**Issue by Remi13520** [seinecle/codapps#79]
<img width="296" alt="aa" src="https://user-images.githubusercontent.com/36775966/36616455-1d6956c8-18e4-11e8-866a-6a257686ecc8.PNG">

à la fin du téléchargement oracle, on m'affiche le message d'erreur "installation of JDK 8 update 161 was not completed, try to run installer again or consult the installation log file for more details" (screenshot ci-joint). J'ai tout essayé, de télécharger une autre version, d'aller voir le log file... Rien ne fonctionne... Je peux essayer sur un autre ordinateur dans les jours qui viennent éventuellement..

**Comment by seinecle** [comment]
... ou vous rendre aux tutoriels du lundi, c'est le genre de problème qui se résout plus facilement en face à face.

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus de 15 jours. Je la  clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la  réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir  cette issue, mais créez-en plutôt une autre.
