### ISSUE TITLE
"Access Denied" à la création d'un nouveau projet

### ISSUE THREAD

**Issue by CharlotteCarteret** [seinecle/codapps#8]
Bonjour, 

j'ai fait les premières étapes qui consistaient à installer le plugin etc., j'ai redémarré NetBeans mais je n'arrive pas à faire l'étape suivante du module 1 sur les mises à jour, rien ne s'affiche quand j'allume Net Beans. 
Merci,

Charlotte CARTERET
![2018-01-29](https://user-images.githubusercontent.com/35915909/35502077-152cb98a-04dc-11e8-852d-11abdd54eebd.png)

**Comment by seinecle** [comment]
Bonjour,

Votre copie d'écran ne montre pas de problème particulier. Si vous essayez de créer un nouveau projet comme indiqué [dans cette leçon](https://seinecle.github.io/codapps/generated-html/creating-your-first-project-and-previewing-your-app.html), rencontrez-vous une difficulté?

**Comment by CharlotteCarteret** [comment]
![2018-01-29 2](https://user-images.githubusercontent.com/35915909/35502436-53dcffea-04dd-11e8-8d3c-310029ac8acb.png)

Oui j'ai accès refusé

**Comment by CharlotteCarteret** [comment]
D'accord. Oui j'ai accès refusé
![2018-01-29 3](https://user-images.githubusercontent.com/35915909/35502593-c4fd5f12-04dd-11e8-85f9-d592f45d9745.png)

**Comment by seinecle** [comment]
Ok. Il s'agit d'une erreur qu'une de vos camarades a déjà rencontrée, nous avons trouvé une solution. Je vous invite à lire [nos échanges ici.](https://github.com/seinecle/codapps/issues/3) (issue #3). Est-ce que cela résout votre problème?

**Comment by CharlotteCarteret** [comment]
Moi je n'arrive pas à résoudre le problème... Bitdefender me dit ne bloquer aucune application.... Et excusez moi je viens de me rendre compte que mon premier message ne veut rien dire

**Comment by seinecle** [comment]
Nous allons continuer à essayer d'identifier le problème ici. Quelle est votre version de Java?

    * Cliquez sur le bouton Démarrer
    * Faites défiler les applications et les programmes répertoriés jusqu'à ce que vous voyiez le dossier Java
    * Cliquez sur le dossier Java, puis sur A propos de Java pour voir la version de Java

**Comment by seinecle** [comment]
Je vais clore cette issue. N'hésitez pas à la réouvrir si vous avez des éléments nouveaux à apporter.
