### ISSUE TITLE
image 

### ISSUE THREAD

**Issue by camillemrnt** [seinecle/codapps#80]
Bonjour , 
J'ai deux problèmes après avoir inséré mon fond d'écran je ne vois plus ma première image et ensuite meme en suivant toutes les instructions mon boutton n'est pas centré
<img width="200" alt="capture d ecran 2018-02-23 a 22 03 30" src="https://user-images.githubusercontent.com/36190228/36616899-c28991d0-18e5-11e8-815e-5dcfe4ab200e.png">

**Comment by seinecle** [comment]
Bonjour,
C'est une question de layout qui se résout difficilement à distance. Passez en tutos le lundi pour qu'on examine la solution.
