### ISSUE TITLE
Taille de l'application trop grande

### ISSUE THREAD

**Issue by leadebrincat** [seinecle/codapps#81]
Bonjour, 
J'ai une erreur Dashboard par rapport à la taille de mon application, qui parait-il est trop grande... Que dois-je faire ? 
Merci par avance. 

<img width="544" alt="erreur" src="https://user-images.githubusercontent.com/36039316/36969949-308491d4-2067-11e8-8f18-aa03f70d0b0d.PNG">

**Comment by seinecle** [comment]
Cette question a reçu une réponse ici: #53 .
