### ISSUE TITLE
Téléchargement des images

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#82]
Bonjour Monsieur, 

Je ne trouve pas comment télécharger les images nécessaires pour l'application... pourriez vous m'aider ? 

Merci

![capture d ecran 2018-03-06 a 11 50 25](https://user-images.githubusercontent.com/35694045/37028493-acf4e548-2134-11e8-83f6-b04b0c443a0d.png)

**Comment by seinecle** [comment]
merci pour cette notification, j'ai réglé cette question. Vous pouvez consulter la leçon et télécharger les images.
