### ISSUE TITLE
Génération des certificats Apple IOS

### ISSUE THREAD

**Issue by PaulineGUEHO** [seinecle/codapps#83]
Bonjour Monsieur Levallois,

Impossible de générer mes certificats IOS.
En cliquant sur "ios" dans propreties puis generate : 
![ios certificates](https://user-images.githubusercontent.com/35836611/37033930-dffad110-2147-11e8-9710-9600bd0d8d18.jpg)

Et en utilisant CodeNameOne Settings, je peux entrer mes identifiants apple, seulement ensuite une page s'affiche qui me demande de sélectionner une "équipe", mais rien n'est disponible sur l'écran et en cliquant sur la flèche droite rien ne se passe ... 
![codenameone settings](https://user-images.githubusercontent.com/35836611/37033972-11e9ce2e-2148-11e8-8d74-220668c60eb6.jpg)

Avez-vous une idée de solution ?

Merci beaucoup ! 
Pauline

**Comment by seinecle** [comment]
Bonjour,

Avez-vous acheté un compte développeur Apple à 99$? Si ce n'est pas le cas, alors c'est l'explication: Apple réserve ses certificats aux développeurs qui ont payé. Regardez plutôt comment faire avec un Android - c'est gratuit pour créer une app sur son propre téléphone (20$ pour publier une app sur le PlayStore).

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus d'une semaine. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
