### ISSUE TITLE
Link is not opening the browser week 2 adding links

### ISSUE THREAD

**Issue by Thuski8** [seinecle/codapps#84]
I did exactly the same mentioned in the video as well as pdf. After running my program, it shows the button, but after clicking the button, nothing appears, browser should opened as shown in the video but nothing appears. Here is the screenshot of the debug:
![screenshot 3](https://user-images.githubusercontent.com/37073538/37037279-503097c4-2195-11e8-9a34-f43498df6b1c.png)
![screenshot 4](https://user-images.githubusercontent.com/37073538/37037280-50669842-2195-11e8-8c0d-d40e155af7ec.png)
![screenshot 5](https://user-images.githubusercontent.com/37073538/37037283-50a3755a-2195-11e8-9908-89b56fd21a54.png)
 I hope to hear from you asap.

**Comment by seinecle** [comment]
Hi,
The course content on Coursera is not up to date so the instructions might lead to this error. Please patient until the end of this month and the new version of the courses will be updated. Sorry for the inconvenience and thank you for your patience.

**Comment by Thuski8** [comment]
But the the coursera has already started the couure and ends in april. Also, it has some deadlines of quiz. Where can i get the updated course? Also the course has taught us to create 2 screen in week 2. But i try to create 3rd screen but there is an error? Where can i get the help?
Thanks for your reply.

**Comment by seinecle** [comment]
The course will be soon updated on Coursera. Sorry for this trouble, and I hope you will enjoy the new version.
