### ISSUE TITLE
Error message in code:  add links.  

### ISSUE THREAD

**Issue by sujinglove** [seinecle/codapps#85]
I got error when I coded to add links, the recommendation is as follow, what should I do with this.: 

Cannot find symbol
symbol: variable Display
Location: class Screen1 

Add import for com.codename1.ui.Display
Create class"Display" in package io.codapps.fashion(Source packages) 
Create class"Display" in io.codapps.fashion.Screen1
Create field"Display" in io.codapps.fashion.Screen1

**Comment by seinecle** [comment]
Hi,
The course content on Coursera is not up to date so the instructions might lead to this error. Please patient until the end of this month and the new version of the courses will be updated. Sorry for the inconvenience and thank you for your patience.
