### ISSUE TITLE
Erreur dans le code

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#87]
Bonsoir Monsieur, 

J'ai essayé de suivre les instructions pour créer le layout mais j'ai des messages d'erreur qui s'affichent...

Merci de votre aide
Bonne soirée

![capture d ecran 2018-03-08 a 19 22 41](https://user-images.githubusercontent.com/35694045/37168847-6d716f6c-2306-11e8-8c7a-89a19d3ce895.png)

**Comment by seinecle** [comment]
En effet: votre ligne 28 juste au dessus semble être problématique. Elle indique:

`BorderLayout:`

Je pense que cette ligne est un commentaire de votre part pour vous repérer dans votre code? C'est une très bonne démarche. Il faut juste ajouter deux `//` au début de votre ligne pour que le code comprenne qu'il ne s'agit pas d'une ligne de code, mais d'un simple commentaire.

Comme ceci:

`// BorderLayout :`

**Comment by Clemencegiry** [comment]
Merci le problème est résolu !
