### ISSUE TITLE
Problème à coder les boucles

### ISSUE THREAD

**Issue by ghost** [seinecle/codapps#88]
![probleme avec loops](https://user-images.githubusercontent.com/35698106/37252839-c8b1b606-2528-11e8-8665-7f532239ad80.PNG)

Même en recopiant le code sur le tutoriel, cela ne fonctionne pour moi ! J'ai un problème à répéter la boucle. Ça me donne cela.

**Comment by seinecle** [comment]
Bonjour,
C'est une petite erreur: vous avez écrit un i majuscule (`I`) alors qu'il fallait un L minuscule (`l`).

C'est dans cette ligne que cela se passe dans le mot **println** : `System.out.println("This is loop"+ i);`

Est-ce que cela résout votre problème?

**Comment by ghost** [comment]
Ok très bien,
Je vous remercie.

Cordialement,
Hilary NOUDJI.

Sent from my iPhone using IBM Verse

On 11 Mar 2018, 16:44:07, notifications@github.com wrote:
