### ISSUE TITLE
Problème dans le "package name", impossible de "preview l'app"

### ISSUE THREAD

**Issue by clemencebureau** [seinecle/codapps#9]
Bonjour, 
Lorsque j'ai voulu Preview my app, un message d'erreur s'est affiché, je crois comprendre que mon package name n'est pas accepté (cf screen), comment faire pour le changer et faire en sorte que cela fonctionne ?
Merci d'avance

<img width="1089" alt="capture d ecran 2018-01-29 a 11 06 02" src="https://user-images.githubusercontent.com/35894248/35504837-6dba40a6-04e4-11e8-9854-b844704951f0.png">

**Comment by seinecle** [comment]
Bonjour,

Effectivement le tiret dans le package name est la source de l'erreur.

Le "package name" est utilisé dans tellement de lignes de code et fichiers de configuration qui constituent votre app, qu'il est difficile voire impossible de le changer sans qu'une de ces lignes, ou un de ces fichiers, ne soit oublié - ce qui causera des bugs dans votre application.
Il n'y a donc pas d'autres solution que d'effacer votre projet et en recommencer un autre.

Je vais mettre à jour [la leçon](https://seinecle.github.io/codapps/generated-html/creating-your-first-project-and-previewing-your-app.html#_1_the_package_name) (je crois qu'il y a déjà un avertissement) pour être absolument clair sur le fait qu'un mauvais package name ne peut pas être rectifié par la suite. Désolé.

**Comment by clemencebureau** [comment]
Pouvez-vous m'expliquer comment le supprimer ? 
Merci

**Comment by clemencebureau** [comment]
Dans ce cas, ai-je le droit de modifier mon adresse mail pour qu'elle corresponde aux critères ??
Merci

**Comment by seinecle** [comment]
Oui bien sûr, faites: fr.orange.clemencebureau

**Comment by clemencebureau** [comment]
Merci de votre aide !
