### ISSUE TITLE
Pas le bon visuel à la fin 

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#90]
Bonsoir Monsieur

J'ai écrit le code du module 6 mais je n'obtiens pas l'écran voulu... En mode preview, j'ai simplement un écran avec "Hi world" 

![capture d ecran 2018-03-11 a 19 23 10](https://user-images.githubusercontent.com/35694045/37256944-154fc7b2-2562-11e8-8761-a4d4797e73fb.png)

**Comment by seinecle** [comment]
Bonjour,

Il faut changer qq lignes dans le fichier MyApplication.java. Voir la réponse que j'ai faite à cette question: #25

**Comment by Clemencegiry** [comment]
Merci !
