### ISSUE TITLE
Ajouter un fond pour l'application cookie cliker 

### ISSUE THREAD

**Issue by valentinthi** [seinecle/codapps#91]
Bonjour, 

Afin d'améliorer le design de l'application, je me demandais si c'était possible de combiner un ajout de fond via Gui Builder avec la form1 qu'on a crée en suivant votre cours (étant donné que cette form n'est pas crée avec Gui Builder mais en codant)

Merci

**Comment by seinecle** [comment]
Bonjour,
Je ne suis pas sûr de comprendre ce que vous voulez dire. Vous pouvez bien sûr ajouter un fond de couleur dans l'app en codant. Si vous l'aviez fait en codant sur un autre Form, même créé avec le gui builder , cela sera les mêmes lignes de code pour votre Form créé en codant. A la place de form1.set.... vous mettrez juste this.set... en prenant soin d'écrire cette ligne dans la fonction "constructeur " (voir Module 6 pour l'explication de cette fonction). Si vous rencontrez des problèmes n'hésitez pas à poster vos questions suivantes ici (si le problème est différent ouvrez une nouvelle issue).

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date de plus d'une semaine. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
