### ISSUE TITLE
Avoir accès à Apple Developer Console

### ISSUE THREAD

**Issue by Clemencegiry** [seinecle/codapps#92]
Bonjour, 
Je n'ai pas reçu le mail permettant d'avoir accès à l'Apple Developer Program pour pouvoir mettre l'application sur iphone.

**Comment by seinecle** [comment]
Bonjour,

Je n'enverrai pas cet email car le processus pour mettre l'app sur un iPhone est extrêmement long, or dans ce cours nous devons également créer une app très longue à coder elle aussi : je préfère que vous portiez tous vos efforts sur cet aspect du cours.
Il y a bien un aspect de la notation de l'assignment 2 qui porte sur le fait de mettre son application sur un téléphone (cela vous donne 2 points supplémentaires) : dans ce cas, je vous demande de trouver dans votre entourage un(e) camarade qui vous prête son téléphone Android pour quelques instants pour le faire. Cela prend littéralement 5 minutes (contre 1 à 2 jours pour un iPhone).

**Comment by Clemencegiry** [comment]
D'accord merci de votre réponse !
