### ISSUE TITLE
vidéos du cours

### ISSUE THREAD

**Issue by fleurBr** [seinecle/codapps#93]
bonjour, dans les modules 5-6 il faut regarder des vidéos mais je ne sais pas ou les trouver.

Merci

Fleur

**Comment by seinecle** [comment]
Bonjour,

Où ces vidéos sont-elles mentionnées? Il n'y en a pas : https://emlyon.github.io/codapps/

**Comment by seinecle** [comment]
Bonjour,

La dernière réponse à cette issue date d'une semaine. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
