### ISSUE TITLE
Code correct mais mauvais rendu dans module 6

### ISSUE THREAD

**Issue by LouiseRzasa** [seinecle/codapps#94]
Bonjour, après avoir recopié toutes les lignes de code du module 6 je n'arrive pas à la bonne image d'app au final, pourriez-vous m'aider? Merci

![capture d ecran 2018-03-12 a 15 51 41](https://user-images.githubusercontent.com/36564530/37290779-7767c0f2-260d-11e8-968b-14e9048d983e.png)
![capture d ecran 2018-03-12 a 15 51 29](https://user-images.githubusercontent.com/36564530/37290780-77b64b3c-260d-11e8-9fa8-3c4ad99f8c6c.png)
![capture d ecran 2018-03-12 a 15 51 04](https://user-images.githubusercontent.com/36564530/37290781-77eca09c-260d-11e8-83dd-c36d9ba5b8eb.png)

**Comment by seinecle** [comment]
Pouvez vous copier coller tout le code de votre Form1 ici svp?

**Comment by LouiseRzasa** [comment]
![capture d ecran 2018-03-12 a 16 08 37](https://user-images.githubusercontent.com/36564530/37291818-c9bacb68-260f-11e8-9182-9f07c749b44c.png)
![capture d ecran 2018-03-12 a 16 08 25](https://user-images.githubusercontent.com/36564530/37291821-ca6fe016-260f-11e8-8a43-937e1fb5cdaf.png)
![capture d ecran 2018-03-12 a 16 08 06](https://user-images.githubusercontent.com/36564530/37291822-caa3ec12-260f-11e8-8429-bb77b814b8e4.png)
![capture d ecran 2018-03-12 a 16 07 49](https://user-images.githubusercontent.com/36564530/37291824-cad58a1a-260f-11e8-85ca-b3016a85497f.png)

**Comment by seinecle** [comment]
Le code lui-meme svp pas une cope d'écran :-)

**Comment by LouiseRzasa** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.louiserzasa.myfirstapp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
/**
 *
 * @author Louise
 */
public class Form2 extends com.codename1.ui.Form {
Resources theme = Resources.getGlobalResources();    
Image farmPic = theme.getImage("farm_50x37.png");
Image clickPic = theme.getImage("click_50x64.png");
Image cookieCentraPic = theme.getImage("cookie_200x200.png");
Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
public Form2() {
    GridLayout gridLayoutThreeByOne = new GridLayout(3, 1); 
    this.setLayout(gridLayoutThreeByOne); 
    this.setScrollable(false);
Container northRegion = new Container();
BorderLayout borderLayoutNorth = new BorderLayout();
northRegion.setLayout(borderLayoutNorth);
Container centerRegion = new Container();
GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
centerRegion.setLayout(gridLayoutFourByOne);
centerRegion.setScrollableY(true);
Container southRegion = new Container();
BorderLayout blSouth = new BorderLayout();
southRegion.setLayout(blSouth);
this.addComponent(northRegion);
this.addComponent(centerRegion);
this.addComponent(southRegion);
ScaleImageButton cookieCentral = new ScaleImageButton(); 
cookieCentral.setIcon(cookieCentraPic); 
cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);
Label scoreLabel = new Label();
scoreLabel.setText("0 cookies");
scoreLabel.getStyle().setAlignment(Component.CENTER);
Label cookiesPerSecondLabel = new Label();
cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);
northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);
MultiButton autoclickButton = new MultiButton("Auto click"); 
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\""); 
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");
MultiButton grandmaButton = new MultiButton("Grandma");
    Image grandmaPic = null;
grandmaButton.setIcon(grandmaPic); 
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");
MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");
centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
centerRegion.add(farmButton);
}
}

**Comment by seinecle** [comment]
N'hésitez pas à sauter des lignes :-)

Qq remarques:

- avez vous importé les images dans theme.res? Sinon elles ne s'afficheront pas. [Voici les instructions](https://emlyon.github.io/codapps/generated-html/layout-design.html#_b_creating_variables_for_the_images_we_added_to_code_theme_res_code).
- vous avez la ligne `Image grandmaPic = null;` il faut la supprimer (car elle dit que la variable grandmaPic ne contient plus rien, il n'y aura donc pas d'image).
- pour votre preview, utilisez un téléphone plus grand que l'iPhone 3, pour être sûr que tout tienne sur votre écran. [Suivez ces instructions](https://emlyon.github.io/codapps/generated-html/creating-your-first-project-and-previewing-your-app.html#_b_adjusting_the_size_of_the_skin_to_the_screen).

**Comment by LouiseRzasa** [comment]
Merci pour les informations. 
Par contre, quand j'enlève la ligne en question, je n'arrive plus à lancer la preview... 
De plus, j'ai bien importé les photos dans theme.res au préalable...

**Comment by seinecle** [comment]
Oh oui pardon. La ligne pour l'image de la "grandma" doit elle aussi importer une image que vous avez placée dans theme.res
Cette ligne doit donc être: `Image grandmaPic = theme.getImage("grandma_50x50.png");`

La région centrale de l'écran est "scrollable": en mode preview, verifiez que vous pouvez scroller vers le bas avec votre souris, et vous devriez voir apparaître ce que vous avez placé à cet endroit (la grandma et la farm).

En revanche je ne m'explique pas l'absence du cookie sur votre preview. Il faudrait que je puisse vérifier que vous avez bien importé l'image dans theme.res. Le nom du fichier importé correspond-il bien à ce que vous avez mis dans le code?

-> je m'explique: si votre fichier s'appelle `cookie_image.png` et que vous l'importez dans themes.res, alors ma ligne de code `Image cookieCentraPic = theme.getImage("cookie_200x200.png");` doit être changée et devenir `Image cookieCentraPic = theme.getImage("cookie_image.png");`

-> le problème vient peut-être d'ailleurs, il faudrait passer en tutoriel le lundi pour diagnostiquer.

Si vous trouvez une réponse à votre problème, merci de la poster ici pour que l'on sache! Merci!

**Comment by LouiseRzasa** [comment]
Bonjour, voilà j'ai essayé d'adapter le code au nom des images dans Image.res mais le rendu n'est toujours pas celui attendu... 
Je vous joins un screen des mes images importées et de la preview puis mon code (je précise que quand je déroule la preview, du texte apparaît mais jamais d'images...) 
![capture d ecran 2018-03-22 a 11 31 05](https://user-images.githubusercontent.com/36564530/37765520-9e49e722-2dc4-11e8-9cc2-9a38b172c2da.png)
![capture d ecran 2018-03-22 a 11 30 15](https://user-images.githubusercontent.com/36564530/37765521-9e79f516-2dc4-11e8-8e1e-3dd217e52a94.png)

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.louiserzasa.myfirstapp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
/**
 *
 * @author Louise
 */
public class Form2 extends com.codename1.ui.Form {
Resources theme = Resources.getGlobalResources();    
Image farmPic = theme.getImage("Tracteur.png");
Image clickPic = theme.getImage("Click.png");
Image cookieCentraPic = theme.getImage("cookie.png");
Image cookiePressedPic = theme.getImage("cookie.png");
public Form2() {
    GridLayout gridLayoutThreeByOne = new GridLayout(3, 1); 
    this.setLayout(gridLayoutThreeByOne); 
    this.setScrollable(false);
    
Container northRegion = new Container();
BorderLayout borderLayoutNorth = new BorderLayout();
northRegion.setLayout(borderLayoutNorth);

Container centerRegion = new Container();
GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
centerRegion.setLayout(gridLayoutFourByOne);
centerRegion.setScrollableY(true);

Container southRegion = new Container();
BorderLayout blSouth = new BorderLayout();
southRegion.setLayout(blSouth);

this.addComponent(northRegion);
this.addComponent(centerRegion);
this.addComponent(southRegion);

ScaleImageButton cookieCentral = new ScaleImageButton(); 
cookieCentral.setIcon(cookieCentraPic); 
cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);

Label scoreLabel = new Label();
scoreLabel.setText("0 cookies");
scoreLabel.getStyle().setAlignment(Component.CENTER);

Label cookiesPerSecondLabel = new Label();
cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);
northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

MultiButton autoclickButton = new MultiButton("Auto click"); 
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\""); 
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");

MultiButton grandmaButton = new MultiButton("Grandma");
Image grandmaPic = theme.getImage("Grandma.png");
grandmaButton.setIcon(grandmaPic); 
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
centerRegion.add(farmButton);
}
}

**Comment by seinecle** [comment]
Désolé pour cette réponse tardive. C'est un mystère. Pouvez vous passer en tuto demain?
