### ISSUE TITLE
Problème de téléchargement des images Cookie Clicker

### ISSUE THREAD

**Issue by ghost** [seinecle/codapps#95]
![probleme de telechargement](https://user-images.githubusercontent.com/35698106/37462361-f8de011e-2851-11e8-9190-48736fa50921.PNG)
Depuis mon ficher PDF, je n'arrive pas à télécharger les images nécessaires pour concevoir Cookie Clicker.
En cliquant sur le nom des fichiers, ça me donne cela:
![probleme de telechargement 2](https://user-images.githubusercontent.com/35698106/37462446-3fa50a98-2852-11e8-9c0b-333562d9840d.PNG)
J'autorise, mais les images ne se téléchargent pas.

**Comment by seinecle** [comment]
Can you try from the web page version?

**Comment by ghost** [comment]
I have tried the web page version.
It's working.
Thanks.

Sent from my iPhone using IBM Verse

On 15 Mar 2018, 13:27:22, notifications@github.com wrote:
