### ISSUE TITLE
l'emplacement de la création d'un label 

### ISSUE THREAD

**Issue by ClovisLF** [seinecle/codapps#96]
Bonjour, 

je suis à la dernière étape du cookie clicker. 
vous nous dite qu'il faut déplacer les lignes de création des labels "scoreLabel" et cookiesPerSecondLabel" au début du fichier mais à quel début faites vous référence ? 
![capture d ecran 2018-03-17 a 11 11](https://user-images.githubusercontent.com/36734464/37554139-d38dc172-29d4-11e8-8524-325f7b4aece0.jpeg)
![capture d ecran 2018-03-17 a 11 12](https://user-images.githubusercontent.com/36734464/37554140-d3a5f1f2-29d4-11e8-8c25-4cdb1a754b0f.jpeg)
![capture d ecran 2018-03-17 a 11 12 20](https://user-images.githubusercontent.com/36734464/37554141-d3bde118-29d4-11e8-8173-507622e0fb79.jpg)

**Comment by seinecle** [comment]
Bonjour,

Ces deux variables que nous avions déclarées dans la méthode public Form1() doivent maintenant être déclarées hors de cette méthode.

Pourquoi?

Parce qu'une variable déclarée dans une méthode n'est "accessible" ("utilisable") que dans cette méthode-là.

L'alternative est donc de déclarer la variable tout au début de la classe, puis de s'en servir dans les méthodes qui en ont besoin.

Nos deux variables sont:

```
Label scoreLabel = new Label();
Label cookiesPerSecondLabel = new Label();
```

Déplaçons ces déclarations de variables ici:

package net.clementlevallois.net.cookieclicker.ultimate;

import com.codename1.ui.util.Resources;
import com.codename1.ui.Image;   

```
public class Form1 extends com.codename1.ui.Form {

  Resources theme = Resources.getGlobalResources();
  Image farmPic = theme.getImage("farm_50x37.png");
  Image clickPic = theme.getImage("click_50x64.png");
  Image cookieCentraPic = theme.getImage("cookie_200x200.png");
  Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
  Label scoreLabel = new Label();
  Label cookiesPerSecondLabel = new Label();
  // etc...

```
J'espère que c'est plus clair?

**Comment by seinecle** [comment]
Bonjour, la dernière réponse à cette issue date de 6 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
