### ISSUE TITLE
Problème à définir et placer les labels

### ISSUE THREAD

**Issue by ghost** [seinecle/codapps#97]
Voici ce que cela me donne !
Je n'arrive plus à ouvrir le preview de l'app.
![probleme a definir les 2 variables](https://user-images.githubusercontent.com/35698106/37554599-80804aa2-29db-11e8-80be-c984467a43b7.PNG)

**Comment by seinecle** [comment]
Bonjour,
Voir ma réponse ici: #96 
Si cela ne vous aide pas je reste à votre disposition.

**Comment by ghost** [comment]
Finalement, 
J'ai regardé cette solution-là.

Cordialement,
Hilary NOUDJI

Sent from my iPhone using IBM Verse

On 19 Mar 2018, 21:20:10, notifications@github.com wrote:
