### ISSUE TITLE
Problème affichage preview & Incrémentation score

### ISSUE THREAD

**Issue by Anton20241997** [seinecle/codapps#98]
Bonjour Monsieur, j'ai quelques soucis avec le dernier module. 

1. Lorsque j'ai preview mon code, voilà ce que j'obtenais : 

![screen shot 2018-03-17 at 22 20 34](https://user-images.githubusercontent.com/35681605/37560061-78c57408-2a31-11e8-9fa4-b282317a5898.png)

Je pouvais tout à fait scroller mais le zoom était beaucoup trop important. 
J'ai donc copié le code fourni au début du chapitre suivant et là : même problème.

2.  J'ai essayé de configurer l'incrémentation du score mais j'ai beau suivre attentivement le cours, lorsque j'appuie sur le bouton, rien ne se passe. 

Voici mon code :

public class Form1 extends com.codename1.ui.Form {

    Resources theme = Resources.getGlobalResources();
    float score = 0f;

    public Form1() {

       

        Image grandmaPic = theme.getImage("grandma_50x50.png");
        Image farmPic = theme.getImage("farm_50x37.png");
        Image clickPic = theme.getImage("click_50x64.png");
        Image cookieCentraPic = theme.getImage("cookie_200x200.png");
        Image cookiePressedPic = theme.getImage("Whishing_Star.png");

      
        GridLayout gridLayoutThreeByOne = new GridLayout(3, 1);
        this.setLayout(gridLayoutThreeByOne);

        this.setScrollable(false);

        Container northRegion = new Container();

        BorderLayout borderLayoutNorth = new BorderLayout();
        northRegion.setLayout(borderLayoutNorth);

       
        Container centerRegion = new Container();

   
        GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
        centerRegion.setLayout(gridLayoutFourByOne);

        centerRegion.setScrollableY(true);

        Container southRegion = new Container();

        BorderLayout blSouth = new BorderLayout();
        southRegion.setLayout(blSouth);

      
        this.addComponent(northRegion);
        this.addComponent(centerRegion);
        this.addComponent(southRegion);

      
        ScaleImageButton cookieCentral = new ScaleImageButton();
        cookieCentral.setIcon(cookieCentraPic);
        cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT);
        cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);

     
        Label scoreLabel = new Label();
        scoreLabel.setText("0  cookies");
        scoreLabel.getStyle().setAlignment(Component.CENTER);

        Label cookiesPerSecondLabel = new Label();
        cookiesPerSecondLabel.setText("0 per second");
        cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER); //centering the text

      
        northRegion.add(BorderLayout.NORTH, scoreLabel);

        northRegion.add(BorderLayout.CENTER, cookieCentral);

        northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

      
        MultiButton autoclickButton = new MultiButton("Auto click");
        autoclickButton.setIcon(clickPic);

        autoclickButton.setTextLine2("\"Get your fingers some rest\"");
        autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
        autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");

    
        MultiButton grandmaButton = new MultiButton("Grandma");
        grandmaButton.setIcon(grandmaPic);
        grandmaButton.setTextLine2("\"Bake cookies with love\"");
        grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
        grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

    
        MultiButton farmButton = new MultiButton("Farm");
        farmButton.setIcon(farmPic);
        farmButton.setTextLine2("\"Harvest cookies every summer!\"");
        farmButton.setTextLine3("each farm produces 3 cookies per second");
        farmButton.setTextLine4("price: 500 cookies. Owned: 0");

  

        centerRegion.add(autoclickButton);
        centerRegion.add(grandmaButton);
        centerRegion.add(farmButton);
        
        cookieCentral.addActionListener(  
                (event) -> {
                    score = score + 1; 
                scoreLabel.setText(score + " cookies");
                }  
        );
    }

}

Merci d'avance ! 👍

**Comment by seinecle** [comment]
Bonjour,

- pour le layout / taille trop grande, changez le skin de votre preview, [comme détaillé ici](https://emlyon.github.io/codapps/generated-html/creating-your-first-project-and-previewing-your-app.html#_b_adjusting_the_size_of_the_skin_to_the_screen).

- pour votre score qui ne s'incrémente pas, c'est un mystère. J'ai collé votre code dans mon app (j'ai créé un nouveau Form pour cette occasion) et le score s'incrémente bien dans la preview. Pourquoi cela ne marche-t-il pas chez vous? Vous cliquez bien sur le cookie n'est-ce pas?

**Comment by Anton20241997** [comment]
Bonjour, 
J'avais fermé le thread car j'ai trouvé les solutions ! Merci pour vos réponses mais concernant le deuxième problème j'ai tout simplement créé un nouveau projet avec le même code et ça a marché :)

**Comment by seinecle** [comment]
Oh je n'avais pas vu. Good!
