### ISSUE TITLE
multiples erreurs

### ISSUE THREAD

**Issue by paulinetaupin** [seinecle/codapps#99]
Bonjour, 

J'ai recopié les lignes et enregistré les images (et retenté une dizaine de fois) mais lorsque je lance le programme, c'est marqué 76 erreurs. Y a t-il quelque chose de spécial à faire en plus ? 
![capture d ecran 2018-03-18 a 08 57 03](https://user-images.githubusercontent.com/35724543/37563883-b60a05c8-2a8a-11e8-8564-a974d2dee7b4.png)

**Comment by seinecle** [comment]
Bonjour,
Nous nous sommes parlé à midi. Est-ce résolu? Sinon, pouvez-vous coller ici votre code (le texte du code, pas une copie d'écran)? Merci.

**Comment by paulinetaupin** [comment]
Bonjour Monsieur, 
 Oui c'est résolu, j'ai demandé à quelqu'un qui avait réussi. Merci beaucoup pour votre mail. 
 Cordialement 
 Pauline Taupin
 
 Le 19 mars 2018 à 14:00:34, notifications@github.com a écrit :
